### ISSUE TITLE
Temperature dependent cross sections

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#129]
As a result of a meeting with @siegela67, @bforget, and Kord Smith, it was decided that an abstraction for representing temperature-dependent cross section data is needed in OpenMC. There are a few paths for achieving this:

1. Store data as-is from multiple ACE tables -- this is what MCNP does currently.
2. Do not store temperature-independent data redundantly. This requires a bit more careful thinking to make sure that only those pieces of data which are temperature-dependent are expressed as such.
3. Use an on-the-fly method (Gokhan's series expansion or Viitanen's explicit temperature treatment).

We decided that the extra work of option 2 was "worth it" because of the large savings in memory and in the interest of the long-term sustainability of the code. Option 3 may hold promise in the future, but it is an active research area that may change.

There are a few important decisions to be made along the way in implementing option 2:

**In a problem with a continuous distribution of temperatures, which temperatures should data be stored at?**

From my discussions with Tim Trumbull at KAPL, one reasonable approach would be to store data at fixed T intervals depending on the desired tolerance.

**What energy grid should be used for the same nuclide/reaction at different temperatures?**

From a memory standpoint, it may make sense to have separate energy grid for each temperature since higher temperatures might not require very fine grids. However, this means that two binary searches are required on each grid when cross sections are interpolated between two temperatures.

**How should interpolation between temperature be performed?**

This was the topic of a [paper by Tim Trumbull](http://www.osti.gov/bridge/purl.cover.jsp?purl=/850499-3VKXSg/850499.PDF). The bottom line is that the conventional wisdom of interpolating on sqrt(T) doesn't necessarily produce better answers.

**Comment by nelsonag** [comment]
@paulromano it looks as if most of the intent of this issue was just closed with #712, though we did not address your question on what temperature grid to store and how to do interpolation.  Thoughts?

**Comment by paulromano** [comment]
Now that we have interpolation and multipole, I'm going to go ahead and close this issue. There will be more improvements in the future I'm sure.

As far as choosing a temperature grid if using interpolation, that is a question that a user will need to answer for their particular application.
