### ISSUE TITLE
Tallying cells not on lowest universe

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#134]
This has been known for a while, but warrants an issue. If a cell filter is used for a tally and the user specifies a cell that contains another universe or lattice, the results will be entirely zeros. The reason is that only the lowest level cell (`p % coord % cell`) is checked and any cells on higher universes are not checked. Thanks to @jessicahunter24 for raising this issue with me.

**Comment by samuelshaner** [comment]
I tried tallying to a cell filled with a lattice and the results came out as expected. Has this issue been fixed?

**Comment by paulromano** [comment]
This issue was resolved some time ago. Note that #484 is not yet resolved however.
