### ISSUE TITLE
Get rid of diffusion score (and transport?)

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#146]
As discussed with @bhermanmit we should probably get rid of the 'diffusion' score. Any reason we shouldn't get rid of 'transport' too?

**Comment by smharper** [comment]
I want to reopen this ancient issue.  The diffusion score was removed but not the transport one.  We should get rid of the transport score, right?

**Comment by nelsonag** [comment]
I have #511 open for this

**Comment by paulromano** [comment]
Closing as duplicate of #511

**Comment by smharper** [comment]
Oh, shucks.
