### ISSUE TITLE
Cell instance filters

### ISSUE THREAD

**Issue by nhorelik** [mit-crpg/openmc#215]
Currently if we want to tally in a specific cell in every lattice position (e.g. if we have rings and slices in the pincells of an assembly, and each position is a unique tally), we can't use universes to specify the geometry in an efficient way.  Instead we need to have different cell objects for each pincell position, and specify all those id's in a cell filter in a tally.  This leads to massive geometry xml files for big problems, and grows the cells and surfaces arrays significantly.  What I'd like is a way to continue using universes to specify geometry, but have the tally system score to a different bin for each instance of a cell that's repeated in a lattice or that appears in other cells that are filled with the universe that contains it.  Essentially I would think this would look like a meshtally, where a scoring index in the results array is determined based on the unique fingerprint of a cell instance (the universe fill and lattice position chain). This could also be how we index the different depleted materials for each instance of a cell that appears in a lattice or fill cell.

**Comment by paulromano** [comment]
This issue is solved by the recent introduction of the "distribcell" filter, merged in #379.
