### ISSUE TITLE
Building with PETSc 3.5.0

### ISSUE THREAD

**Issue by mairi17** [mit-crpg/openmc#293]
I found this would not build with PETSc 3.5.0 due to the PETSC_DEFAULT_DOUBLE_PRECISION reference in the file /home/ec2-user/openmc/src/solver_interface.F90

From Petsc release notes (http://www.mcs.anl.gov/petsc/documentation/changes/35.html)
"PETSC_DEFAULT_DOUBLE_PRECISION has been replaced with PETSC_DEFAULT_REAL"

**Comment by bhermanmit** [comment]
This was solved and released in version 0.6.2.
