### ISSUE TITLE
Stochastic placement of cells (for TRISO fuels)

### ISSUE THREAD

**Issue by smharper** [mit-crpg/openmc#324]
I'm working on a random geometry feature similar to what is described in LA-UR-04-8668 for MCNP.  It is mostly finished, but I will wait on the PR until #313 is closed because it makes this feature much easier to implement.

**Comment by smharper** [comment]
This issue has gotten a little stale, and I think I would like to close it, un-resolved as it is.  I implemented the algorithm, but I don't think it is worth merging in.  It adds a lot of code and input bloat, and it also didn't provide a very random placement for the packing fractions we were interested in.

I think the superior way to model TRISO reactors is to make a script that automatically generates geometry.xml files with TRISOs explicitly placed in their positions.  I was much happier with the results from that approach.  I don't think it's appropriate to include such a script in the OpenMC repo (except maybe as an example?).  So, yeah.  I'm closing this.

**Comment by wbinventor** [comment]
Make it an example IPython Notebook!

On Tue, Aug 11, 2015 at 11:15 PM, Sterling Harper <notifications@github.com>
wrote:

> This issue has gotten a little stale, and I think I would like to close
> it, un-resolved as it is. I implemented the algorithm, but I don't think it
> is worth merging in. It adds a lot of code and input bloat, and it also
> didn't provide a very random placement for the packing fractions we were
> interested in.
>
> I think the superior way to model TRISO reactors is to make a script that
> automatically generates geometry.xml files with TRISOs explicitly placed in
> their positions. I was much happier with the results from that approach. I
> don't think it's appropriate to include such a script in the OpenMC repo
> (except maybe as an example?). So, yeah. I'm closing this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-crpg/openmc/issues/324#issuecomment-130182551>.
>



-- 
Will Boyd
Nuclear Science & Engineering
Massachusetts Institute of Technology
Cell: 423.413.8469
wbinventor@gmail.com

**Comment by paulromano** [comment]
That would be a great example that we could point people to!
