### ISSUE TITLE
fixed source leakage fraction > 1.0

### ISSUE THREAD

**Issue by walshjon** [mit-crpg/openmc#352]
A 14.1 MeV fixed source in a 2.0x2.0x2.0 cm vacuum BC cube of Fe-56 or Pb-208 (ENDF71x data) will give a leakage fraction greater than unity.

**Comment by paulromano** [comment]
I suppose this is theoretically possible with (n,2n) and (n,3n) reactions. If that's really the source of what you're seeing, I'm not sure I would consider it a bug.

**Comment by walshjon** [comment]
I buy that.  It only seems to crop up when (n,2n) becomes reasonably likely.  Thanks @paulromano.
