### ISSUE TITLE
Overlapping cells outside lattices

### ISSUE THREAD

**Issue by smharper** [mit-crpg/openmc#358]
There is currently a bug the lattice code that causes cell overlap errors outside of certain lattices.  [Here's a simple example demonstrating the error.](http://web.mit.edu/smharper/Public/lattice_overlap_fail.tgz)  I'll copy the geometry.xml here so I can explain:

```xml
<?xml version="1.0"?>
<geometry>
  <surface id="11" type="z-cylinder" coeffs="0.0 0.0 0.5"/>
  <cell id="11" universe="11" material="40" surfaces="-11"/>
  <cell id="12" universe="11" material="41" surfaces="11"/>


  <lattice id="21" type="rect" dimension="2 2" lower_left="-2.0 -2.0"
    width="2.0 2.0" outside="41">
    <universes>
      11 11
      11 11
    </universes>
  </lattice>


  <surface id="31" type="z-cylinder" coeffs="0.0 0.0 1.5"/>
  <cell id="31" universe="31" material="41" surfaces="-31"/>
  <cell id="32" universe="31" fill="21" surfaces="31"/>


  <surface id="101" type="z-cylinder" coeffs="0.0 0.0 5.0" boundary="vacuum"/>
  <cell id="101" universe="0" fill="31" surfaces="-101"/>
</geometry>
```

If we plot this geometry, the output we get should look like this:
![correct](https://cloud.githubusercontent.com/assets/4622797/5986483/43675bd0-a8c7-11e4-95b1-34ffd553a7d3.png)

but instead, we get the following error:
```
Overlapping cells detected: 31, 32 on universe 31
```

This error comes from the plotter calling `find_cell` on points outside the lattice.  Consider the point xy = (3.0, 3.0).  At first, `find_cell` correctly identifies that the points are in universe 31 and outside the lattice, then we come across this chuck of code in geometry.F90 that contains the error:

```fortran
            if (.not. outside_lattice) then
              ...
            else

              ! Set universe as the same for subsequent calls to find_cell
              p % coord % next % universe = p % coord % universe

              ! Set coord cell for calls to distance_to_boundary
              p % coord % next % cell = index_cell

            end if
```

So now, the particle's next coordinate level is also in this same universe 31, but the xyz is shifted to a local lattice tile (in this case, tile (3, 3)).  The particle's coordinate hierarchy looks like this:
```
1.  Universe 0,  cell 101, xy = (3.0, 3.0)
2.  Universe 31, cell  32, xy = (3.0, 3.0)
3.  Universe 31, cell  32, xy = (1.0, 1.0)
```

`find_cell` exits fine, but now check_cell_overlap is called, and it will fail on that bottom coordinate level because the point xy = (1.0, 1.0) is actually inside surface 31 and hence cell 31.

**Comment by smharper** [comment]
I want to solve this issue by changing the lattice specification so that we specify outside universes rather than outside materials.  This outside universe would tile infinitely beyond the bounds of the lattice.  This would break backwards compatibility with the geometry.xml, but I think it is the cleanest solution to this problem.  And as a bonus, this would also give us a way to impose periodic boundary conditions; just put your fuel assembly universe as the lattice's outside universe.  Does anyone have strong objects, or ideas for a better solution?

**Comment by wbinventor** [comment]
I like this idea for a different reason than the ones you've highlighted here (though I agree they are good reasons). Universes outside of lattices will permit easier high-fidelity tallies in between lattices. Right now you have to create a separate (dummy, or redundant) material outside of each lattice to tally within if you want the region outside each lattice to be treated separately. With a universe composed of cells, we can "chop" up the region outside of each lattice, and use the distribcell tallying feature that is in beta to perform this type of tallying much more efficiently.
