### ISSUE TITLE
a Link should be up-to-date in the project's User Guide

### ISSUE THREAD

**Issue by PaleNeutron** [mit-crpg/openmc#364]
I found a failed link in your project website and do not know how to connet to you.

In this page https://mit-crpg.github.io/openmc/usersguide/beginners.html

Links in 'the DOE Fundamentals Handbook on Nuclear Physics and Reactor Theory Volume I and Volume II.' are failed.

**Comment by paulromano** [comment]
Fixed in 5d9738be110ac566305daab01a5d23df3de180bd
