### ISSUE TITLE
Pandas Dataframes for Tallies

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/openmc#382]
To facilitate tally data processing in Python, the ``Tally`` class in the Python API should be extended to allow for tally data to be automatically transformed into a [Pandas](http://pandas.pydata.org/) ``dataframe`` structure. The dataframes in Pandas are modeled after dataframe data structures in [R](http://www.r-project.org/) to store data tables in a more intuitive and accessible format than opaque NumPy arrays. The most obvious difference from NumPy arrays to the user is that dataframes more readily support mixed-type columns (*i.e.*, strings and numbers), and allow the use of ``dict``-like keys or labels to index into each column. 

This feature would enable easy analysis with many of Python's powerful statistics packages, including [scikit-learn](http://scikit-learn.org/stable/) which are well integrated with Pandas. In addition, dataframes would permit a much more flexible ``Tally.get_value(...)`` or ``Tally.get_values(...)`` method Finally, tally data in a dataframe could be reported to the user in a much more informative tabular format in interactive Python environments like [IPython Notebook](http://ipython.org/notebook.html) / [Jupyter](https://jupyter.org/) than NumPy arrays.

I envision that this feature would keep the current ``StatePoint`` and ``Tally`` implementations in the Python API intact, which only have NumPy as a required dependency. A ``Tally.build_pandas_dataframe(...)`` class method would build a Pandas dataframe, using numeric and character string data from the filters and scores associated with each of the tally bins. 

Although I would very much like this feature for my own work, I may not get around to implementing it until I have a free day this summer. I'm just posting this now as a reminder to myself and to see if there is any interest or related ideas from other OpenMC developers or users.

**Comment by paulromano** [comment]
Closed with the merging of #393
