### ISSUE TITLE
Test failing to produce tallies.out

### ISSUE THREAD

**Issue by smharper** [mit-crpg/openmc#401]
I'm in the process of reformatting the tests and I noticed an error with "test_filter_distribcell".  Running OpenMC in the "case-3" directory produces no "tallies.out" even though OpenMC claims to be "Reading tallies XML file..."

**Comment by wbinventor** [comment]
That would be because of the following tag in the settings.xml file:

<output tallies="false" />

Set thus to true and you'll see a tallies.out file appear. This is not at
all unique to distribcell tallies.

**Comment by smharper** [comment]
Well that's embarrassing.  Thanks for saving me before I got neck deep in the debugging.
