### ISSUE TITLE
Logarithmic Grid issue for Nuclides with Emax > 20 MeV

### ISSUE THREAD

**Issue by nelsonag** [mit-crpg/openmc#406]
Some nuclides (e.g., 8016 from ENDF-VII.1) have maximum energies in the data of 150 MeV where as the logarithmic_grid routine in energy_grid.F90 assumes a maximum energy of 20 MeV.  

This forces an out of bounds error in cross_sections.F90:calculate_nuclide_xs when when u is larger than the allocated nuc % grid_index.

(As a side note, suggest also using <= in the 2 `elseif (E >= nuc % energy(nuc % n_grid)) then` lines of this calculate_nuclide_xs routine.)

**Comment by walshjon** [comment]
@paulromano and I had discussed this a bit in #335 and settled on disallowing source energies above 20 MeV to avoid the case of not being able to interpolate cross sections in the cases where you have nuclide(s) with evaluations ending at 20 MeV.  If you're seeing that out of bounds error, are we getting > 20 MeV neutrons from someplace?

**Comment by nelsonag** [comment]
Ah-ha! That makes sense.  No I am using it outside of the transport kernel
itself so that made it possible to get particle energies > 20 MeV.  Would
you like me to leave this PR here as a reminder for what you talked about
in #335 or remove it?

**Comment by walshjon** [comment]
Alright, sounds good. Either way is fine with me.  Doesn't hurt to have this reminder since the earlier discussion was buried within the rest of the PR review.

**Comment by paulromano** [comment]
Actually, I would say the problem is really if a nuclide has an energy grid with a max of less than 20 MeV. Be-7 in ENDF/B-VII.1 is actually broken such that the maximum is less than 20 MeV, so it will break the algorithm right now. This reminds me that I should implement something to automatically check for the highest min E and the lowest max E to use across the code.

**Comment by walshjon** [comment]
Is that another ACE library issue?  I'm able to run endf71x Be-7 data w/o incident.

**Comment by paulromano** [comment]
It's possible that whoever produced that library fixed up Be-7. In the ENDF file the maximum energy is 8.1 MeV.

**Comment by walshjon** [comment]
Yes, that must have taken some extra special expert judgement - as you say, ENDF6 cuts off at 8.1 MeV!
