### ISSUE TITLE
Distribcell tally reporting for nested hexagonal lattices is incorrect

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/openmc#411]
Per [this](https://groups.google.com/forum/#!topic/openmc-users/PiTNpttWXOA) thread on the Google users group, there is a bug in the way that distribcell tallies are reported in "tallies.out" for nested hexagonal lattices. From my quick analysis, it appears that the distribcell algorithm counts and tallies the correct number cell instances throughout a nested hex geometry, but builds incorrect and inconsistent string "paths" for the "tallies.out" file for each instance. Hence, the bug is very likely in the ``find_offset(...)`` routine in [src/offset.F90](https://github.com/mit-crpg/openmc/blob/develop/src/output.F90#L2191).

I probably won't have time to look into this for two days. @smharper, do you have an hour or so to try to figure this one out? You may find the issue faster than I since hex lattice indexing is still a bit over my head.

**Comment by smharper** [comment]
I don't know what's causing this yet, but I've narrowed it down a little bit.  We can reproduce the error with "/examples/python/lattice/hexagonal/build-xml.py" as-is (which means it isn't unique to nested lattices).  We can get a simpler test case by replacing the lattice in that example with

```python
lattice = openmc.HexLattice(lattice_id=5)
lattice.center = [0., 0.]
lattice.pitch = [1.]
lattice.universes = [ [univ1]*6, [univ1] ]
```

In that case, the (0, 1) position doesn't show up properly in tallies.out.  After some quick experiments, it looks like the (0, n_rings) position is always missing (using a non-nested, 2d lattice; the more complex lattice from openmc-users doesn't show this same pattern).
