### ISSUE TITLE
Unintuitive statepoint.py workflow

### ISSUE THREAD

**Issue by friedmud** [mit-crpg/openmc#420]
Doing the following:

```python
from openmc import statepoint

sp = statepoint.StatePoint('../openmc/statepoint.100.h5')
sp.read_results()

tally = sp.get_tally(id=1)

print tally.mean
```

Will print `None`... meaning that `tally.mean` hasn't been set/computed yet.

After digging around a bit it seems that the secret sauce is that you need a `tally.compute_std_dev()` call which has a side effect of computing the mean.  This is somewhat non-intuitive :-)

I'd recommend that either accessing the mean would compute the mean (if it hasn't already been computed) or add a new function like `tally.compute_mean()` which would be a bit more obvious.

**Comment by wbinventor** [comment]
I think you raise a very good point. Perhaps we should hide the user from
the "compute_std_dev" and a new "compute_mean" routines entirely. Instead,
the "Tally.mean" and "Tally.std_dev" property decorators could call these
routines if necessary before returning the data. What do you think
@friedmud @smharper @paulromano?

**Comment by smharper** [comment]
I agree, that it would be best to add `compute_std_dev()` to the `mean` and `std_dev` decorators

**Comment by smharper** [comment]
Actually, why don't we just call `compute_std_dev` in `__init__`?

**Comment by wbinventor** [comment]
Because the same Tally class is also used to generate input XML files.

**Comment by smharper** [comment]
Okay.  We could also have `StatePoint.read_results()` call `compute_std_dev()` on all it's tallies.

While we're going down this road, why do we have to call `StatePoint.read_results()`.  That could be done on `__init__`, right?

**Comment by wbinventor** [comment]
Well I'm not so sure about that. I think it might be good for @nhorelik to
comment on this. One of my concerns about automatically reading in results
for all tallies upon initialization is that this won't scale for larger
tally datasets, e.g., the TB-scale datasets that we will soon be able to
compute with DD. It seems to me that we will want to load results for
tallies in a more distributed fashion. Of course to do this will require a
more sophisticated version of "read_results()" than what we currently have.
Perhaps @nhorelik can comment on what he has coming in this regard.

**Comment by smharper** [comment]
Okay, fair point.  I'll go back to voting for calling `compute_std_dev` in the getter decorator.

**Comment by paulromano** [comment]
Yes, the reason that read_results is its own method method right now is exactly what @wbinventor alluded to -- that a user might not want to load all the tally results if they are extremely large (i.e., exceed the physical memory available). That being said, it does seem sensible to compute means and standard deviations on-demand through the properties.

**Comment by friedmud** [comment]
Yeah - I was thinking a property decorator would be the right choice here.

**Comment by wbinventor** [comment]
I just opened #421 which I hope addresses your concerns at least somewhat @friedmud. Let us know if you think this could be simplified further. As @paulromano and I mentioned above, the ``StatePoint.read_results()`` routine is a necessary evil as we move towards processing statepoint files that are larger than the memory on a single node. Perhaps we could check the size of the file in the ``StatePoint`` constructor and load it in if it is small enough - what do folks think of that?

**Comment by friedmud** [comment]
I would vote against having inconsistent behavior based on the file size...

Think about it... you've made up a script that is working on your small "testing" runs on your workstation.  You're happy with it so you run something big on a cluster.  Then you try to apply your script... and it doesn't work (because the file size is too big so now you have to call `read_results()` manually).

Inconsistent behavior would be a larger pain than just knowing that you need to call `read_results()` :smile: 

Thanks for changing the interface here.  The changes look great!

**Comment by wbinventor** [comment]
Good points @friedmud, I was just thinking out loud. If you are happy with the current fix, then so am I.

**Comment by smharper** [comment]
Closed with #421

**Comment by smharper** [comment]
Thanks for reporting this, @friedmud

**Comment by friedmud** [comment]
No problem!  Thanks for the quick fix and good discussion everyone!
