### ISSUE TITLE
Hosted develop branch documentation

### ISSUE THREAD

**Issue by smharper** [mit-crpg/openmc#439]
I think we should host the documentation for the develop branch somewhere.  Bonus points if it automatically updates every time develop changes (could be a nightly build type thing).  Extra bonus points if it also displays the documentation for open PRs.

**Comment by paulromano** [comment]
I think [Read The Docs](https://read-the-docs.readthedocs.org/en/latest/features.html) could be one possible solution.

**Comment by paulromano** [comment]
I have a [readthedocs](https://github.com/paulromano/openmc/tree/readthedocs) branch that I am planning to PR after the 0.7.1 release that will allow us to build documentation on Read The Docs.

**Comment by wbinventor** [comment]
Awesome @paulromano!
On Dec 23, 2015 8:37 AM, "Paul Romano" <notifications@github.com> wrote:

I have a readthedocs <https://github.com/paulromano/openmc/tree/readthedocs>
branch that I am planning to PR after the 0.7.1 release that will allow us
to build documentation on Read The Docs.

—
Reply to this email directly or view it on GitHub
<https://github.com/mit-crpg/openmc/issues/439#issuecomment-166939063>.
