### ISSUE TITLE
Python API tests

### ISSUE THREAD

**Issue by smharper** [mit-crpg/openmc#450]
We need to add tests for the Python API.  Rather than simply adding a new test suite though, I think we should consider making _all_ of the tests use the API.

I think this will give us two advantages:  First, it means that we can be sure that all of OpenMC's tested features work in the API.  Second, it can remove redundancy from our test suite by having our tests inherit a common set of geometry and materials.

Of course, we would need to verify the correctness of the API's output.  For that purpose, I would recommend that we store a hash of the correct .xml files for each test.

Do you guys agree?

**Comment by wbinventor** [comment]
I am definitely in support of this. My comment about tests for the Python API in #449 was motivated by the need to verify the full array of post-processing features in the API (such as those used in the example IPython Notebooks). However, I agree that inherently binding the test suite to the API's input generation capabilities might be just as important.

Personally, if we decide this is the right approach to take, I'm not prepared to switch the test suite over with the limited time I have at the moment. However, I do want to submit a PR with some tests for tally post-processing, probably after my PR with major additions to tally arithmetic to support an ``openmc.mgxs`` submodule. So I can at least contribute something towards this issue in the nearish term.

**Comment by paulromano** [comment]
I am strongly in support of this too. I think all of us realize the test suite is not catching as much as it should. I'm fine with a gradual approach as @wbinventor suggests. By submitting this issue @smharper, does that imply you are volunteering to implement it? :wink:

**Comment by paulromano** [comment]
Also, whoever is attacking this might want to handle #262 simultaneously.

**Comment by smharper** [comment]
I'll probably regret this later, but sure.  It looks like most of it can be knocked out with just a couple evenings and a few fingers of whiskey.

**Comment by smharper** [comment]
I'm not going to close this because there is still more work to do, but I am going to remove my assignment and take it off the milestone because I really should focus on other projects for a while.

**Comment by paulromano** [comment]
That's fair. Thanks for making the first strides!

**Comment by smharper** [comment]
We haven't moved our entire test suite to the Python API, but I think the PyAPI testing infrastructure is established well enough that we can close this issue.
