### ISSUE TITLE
Python API errors out when trying to import state points with old specifications

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/openmc#464]
When using the latest version of the python API with state point files generated with older versions of OpenMC, the Python API breaks when trying to import the state point file. As the error below shows, the numpy.ndarray filetype cannot be decoded so the API errors out before the revision check:

            94         # Ensure filetype and revision are correct
            95         if 'filetype' not in self._f or self._f[
     --->   96                 'filetype'].value.decode() != 'statepoint':
            97             raise IOError('{} is not a statepoint file.'.format(filename))
            98         if self._f['revision'].value != 14:

            AttributeError: 'numpy.ndarray' object has no attribute 'decode'

Also, as an aside, the state point revision number on the documentation on github [(link)](https://github.com/mit-crpg/openmc/blob/af6c1412bb110a2d2e88005508725a3d6a68f129/docs/source/usersguide/output/statepoint.rst) says 13, but I think it should be 14 as it differs from the state point specification 13 on the openmc website documentation.

**Comment by paulromano** [comment]
Thanks for pointing this out @samuelshaner. I'll put in place some kind of better check there. You're right aobut the revision number; I'll fix that too.
