### ISSUE TITLE
Tally with cell filter assumes the cells tallied to are mutually exclusive

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/openmc#484]
If a tally is created with a cell filter, the bins (i.e. cells) are assumed to be mutually exclusive. For instance, we can modify the `examples/xml/lattice/simple/tallies.xml` file for a 4x4 lattice of pin cells to only have the following tally:

    <tally id="1">
      <filter type="cell" bins="1 101" />
      <scores>total</scores>
    </tally>

Where cell `1` is the cell filled with the lattice and cell `101` is a the fuel region of one of the pins. The `tallies.out` file would be:

    ============================>     TALLY 1     <============================

    Cell 1
      Total Material
        Total Reaction Rate                  1.09346        +/- 6.47323E-03
    Cell 101
      Total Material
        Total Reaction Rate                  0.0            +/- 0.0

The tallies over the two cells can be put into separate tallies as follows:

    <tally id="1">
      <filter type="cell" bins="1" />
      <scores>total</scores>
    </tally>
    <tally id="2">
      <filter type="cell" bins="101" />
      <scores>total</scores>
    </tally> 

Yielding the desired results:

    ============================>     TALLY 1     <============================

    Cell 1
      Total Material
        Total Reaction Rate                  1.09346        +/- 6.47323E-03

    ============================>     TALLY 2     <============================

    Cell 101
      Total Material
        Total Reaction Rate                  4.99603E-02    +/- 4.27083E-04

The openmc API will merge tallies with cell filters assuming that the cells are mutually exclusive so this issue should be addressed in both the Fortran code and Python API.

As far as I can see, the documentation does not indicate that bins for the cell filter must be mutually exclusive. Fixing this issue seems like it might be difficult and waiting for the tally module to be refactored could be the best option.

**Comment by wbinventor** [comment]
I agree that a fix for this might wait until the tally module has been
refactored...whenever that will be. To adjust the Python API to check for
this would require a large extension of the geometric capabilities in the
API; in particular, detection of overlapping cells in this case. Althoigh
this might be desirable, I think that a more realistic solution is to embed
the error checking in the back end.

**Comment by paulromano** [comment]
Yeah, this is going to take an algorithmic change that might require data structure changes as well, so I also agree that it makes sense to do this as part of a refactor.
