### ISSUE TITLE
Inverse velocity and delayed nu fission analog and collision tallies should use p % last_E

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/openmc#497]
The inverse velocity and delayed nu fission tallies currently uses `p % E` for querying the neutron velocity, `yield_delayed`, and `nu_delayed` for all tally types. Since the analog and collision tallies are called *after* the neutron has a collision, the energy of the neutron before the collision should be used in querying these values. Thanks to @nelsonag for pointing this out.

**Comment by paulromano** [comment]
#498 fixed this
