### ISSUE TITLE
To have whitespace, or not to have whitespace, that is the question

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#510]
In some of my recent PRs, I've received scorn for not using whitespace around the derived type dereferencing operator, %, since almost all (but not all) of the code uses whitespace around it, e.g.

``` fortran
p % coord(j) % xyz = p % coord(j) % xyz + distance * p % coord(j) % uvw
```

I've started not using whitespace around % after reflecting on it for some time. It is rare in other languages to see whitespace used in such a manner, and I feel that it often makes things lengthier than they need be, especially if there is a series of nested derived types. It also seems to make it clearer that it is a "higher-precedence" operator (although, in fact, it is not event a true 'operator' in Fortran in the sense that it has a precedence relative to other numeric and logical operators). Lastly, all examples in the Fortran standard itself do not use whitespace around %.

So, I'm proposing we start consistently using % with no whitespace around it. The one downside I see is that % is a relatively clunky character, so it does tend to look a little more cluttered, especially when you compare it to, say, the structure reference operator in C. That being said, if most others feel that we should continue using whitespace, we can stick with the current practice. Either way, let's make a decision and add it to the style guide.

**Comment by nelsonag** [comment]
To be honest, I like the whitespace.  MPACT does it without the whitespace and it became quite difficult to work with for me and a few others.

The reason why is b/c the dereferencing operator in Fortran is so wide that it makes it hard for my eyes to easily pull it out as a differentiator between object and derived type.  Contrast that with the `.` in C and Python: the `.` is short and skinny and gets out of the way so the extra space there makes it easy for the eye to find.  I think you can see this in the example below.
```
p % coord(j) % xyz = p % coord(j) % xyz + distance * p % coord(j) % uvw
p.coord(j).xyz = p.coord(j).xyz + distance * p.coord(j).uvw
p%coord(j)%xyz = p%coord(j)%xyz + distance * p%coord(j)%uvw
```

Finally, I agree the additional whitespace does make the lines longer, but I think the clarity is worth it.

**Comment by wbinventor** [comment]
I agree with @nelsonag's sentiment here.

**Comment by samuelshaner** [comment]
I agree with @nelsonag as well.

**Comment by walshjon** [comment]
I like the whitespace... except if the line is coming in at 81 characters.  Then it has to go!  Picking just one for the style guide, though, I also vote for having the whitespace.

**Comment by smharper** [comment]
+1 for the whitespace camp

**Comment by paulromano** [comment]
Looks like I've been handily out-voted! I'll go ahead and change all my non-whitespaced % operators back to having whitespace. Thanks for chiming in everyone!

**Comment by paulromano** [comment]
This is now part of our [style guide](http://openmc.readthedocs.io/en/latest/devguide/styleguide.html#whitespace-in-expressions).
