### ISSUE TITLE
Density units 'sum' is vaguely defined in the documentation

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/openmc#517]
In the documentation, the density element for a material is described as:

    An element with attributes/sub-elements called value and units. The value attribute
    is the numeric value of the density while the units can be “g/cm3”, “kg/m3”, “atom/b-cm”,
    “atom/cm3”, or “sum”. The “sum” unit indicates that the density should be calculated 
    as the sum of the atom fractions for each nuclide in the material. This should not be 
    used in conjunction with weight percents.

Atom fractions have no units, so it is not clear what the density of the material would be (in any set of units) if `units` were set to `sum`. Looking at the source code in `input_xml.F90`, if the units is set to `sum` then it appears the atom fractions are presumed to be the atom densities in `atom/b-cm`. Is this correct? Either way, it would be nice if this was explained in the documentation for inputing materials.

**Comment by paulromano** [comment]
Good point. I'll get that fixed.

**Comment by samuelshaner** [comment]
Fixed with PR #520
