### ISSUE TITLE
Duplicate scores in tally

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/openmc#531]
Currently, duplicate scores in a tally are treated as separate scores resulting in identical outputs to the tally file and unnecessary work tallying the same result more than once. For example, for the following tally:

```
<tally id="1">
    <scores>total total</scores>
</tally>
```

the following results are output to tallies.out:

```
============================>     TALLY 1     <============================

Total Material
  Total Reaction Rate                  30.6489        +/- 6.46755E-02
  Total Reaction Rate                  30.6489        +/- 6.46755E-02
```

Having duplicate scores output duplicate results complicates things for the Python API since only one score will be added to the `_scores` attribute of the Tally, but all duplicate results will be saved in `sum` and `sum_sq`. 

It seems that we would want to avoid duplicate scores in a tally to avoid unnecessary work. Does anyone see any issues with removing duplication scores from tallies?

**Comment by wbinventor** [comment]
+1 for ignoring duplicate scores

**Comment by smharper** [comment]
I see no issue with ignoring duplicates

**Comment by paulromano** [comment]
I'm fine ignoring duplicates. It would be sensible to give the user a warning that they have duplicates though. Is there a practical situation where duplicates occur?

**Comment by samuelshaner** [comment]
I don't see any common use cases where duplicate scores would be encountered, but there are a few not so common cases where they would occur:

* Tallying multiple scattering expansions (e.g. `scatter-P3` and `scatter-P4`).
* Tallying the n2n reaction with by its name, `n2n`, and reaction type, `16`. While not a common case, both of these tallies are in `test_scores_MT`. PR #534 removes the `n2n` tally from this test.

As discussed in PR #525 and #534, I don't think this is an issue many people will encounter, but it is an issue where OpenMC supports duplicate scores whereas the Python API does not.

**Comment by paulromano** [comment]
I believe this was addressed a long time ago. Duplicate scores are no longer allowed.
