### ISSUE TITLE
Question:   how to configure the following error?

### ISSUE THREAD

**Issue by javed123456** [mit-crpg/openmc#536]
I tried all mentioned steps in the Readme but unable to make it workable. When I tried to run ```openmc```, I got the following error:
```ERROR: Settings XML file 'settings.xml' does not exist! In order to run OpenMC,
        you first need a set of input files; at a minimum, this includes
        settings.xml, geometry.xml, and materials.xml. Please consult the user's
        guide at http://mit-crpg.github.io/openmc for further information.
ERROR STOP ```

The thing is I am unable to find the ```settings.xml```. Kindly guide me how to get through this point.

**Comment by paulromano** [comment]
As the error says, you need a set of input files that describe the problem you are running. By itself, OpenMC, can't do anything. There is a description of the input files within the [documentation](http://mit-crpg.github.io/openmc/usersguide/input.html).

Also, please send an email to the [user's group](https://groups.google.com/forum/#!forum/openmc-users) when you have a question about basic use of the code. Issues on github should be reserved for confirmed bugs.
