### ISSUE TITLE
Puzzling Segmentation Fault

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/openmc#552]
I recently had a case throw a segmentation fault and have no idea what may have caused it. This was for the same geometry / materials model as discussed in #546 except with an outer `universe` set on the fuel assembly lattice. I ran this problem with 10,000,000 particles per batch with 10 inactive and 100 total batches (a single generation per batch) on nsecluster with 5 nodes of 6 processes each for 30 processes total (the segfault also occurred with 5 nodes of 12 processes each). The input and output files can be found on my Dropbox [here](https://www.dropbox.com/sh/7zerrhcxpnwu4nw/AABVO9jkuwfGACIvRzYwT-HSa?dl=0).

A particle is lost during batch 9 (an inactive batch) after simulating over 80,000,000 histories. The output from the job scheduler's standard output log file is the following:

```bash
...
 Reading settings XML file...
 Reading cross sections XML file...
 Reading geometry XML file...
 Reading materials XML file...
 Reading tallies XML file...
 Building neighboring cells lists for each surface...
 Loading ACE cross section table: 92235.71c
 Loading ACE cross section table: 92238.71c
 Loading ACE cross section table: 8016.71c
 Loading ACE cross section table: 1001.71c
 Loading ACE cross section table: 5010.71c
 Loading ACE cross section table: 40090.71c
 Maximum neutron transport energy: 20.0000 MeV for 92235.71c
 Initializing source particles...

 ===========================================================================
 ====================>     K EIGENVALUE SIMULATION     <====================
 ===========================================================================

  Bat./Gen.      k            Average k         
  =========   ========   ====================   
        1/1    1.02443                       
        2/1    1.02390                       
        3/1    1.02383                       
        4/1    1.02458                       
        5/1    1.02425                       
        6/1    1.02418                       
        7/1    1.02428                       
        8/1    1.02347                       

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 255
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

 with the following error reported in the job scheduler's error file log:

```bash
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
openmc             000000000045EE76  tally_mp_score_ge         836  tally.F90
openmc             000000000045E013  tally_mp_score_tr        1285  tally.F90
openmc             0000000000529706  tracking_mp_trans         109  tracking.F90
openmc             0000000000473667  simulation_mp_run          91  simulation.F90
openmc             000000000046BF5C  MAIN__                     19  main.F90
openmc             0000000000403AAC  Unknown               Unknown  Unknown
libc.so.6          0000003549A1ED5D  Unknown               Unknown  Unknown
openmc             00000000004039A9  Unknown               Unknown  Unknown
[proxy:0:0@n003.cluster.com] HYD_pmcd_pmip_control_cmd_cb (./pm/pmiserv/pmip_cb.c:886): assert (!closed) failed
[proxy:0:0@n003.cluster.com] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:0@n003.cluster.com] main (./pm/pmiserv/pmip.c:206): demux engine error waiting for event
[proxy:0:1@n004.cluster.com] HYD_pmcd_pmip_control_cmd_cb (./pm/pmiserv/pmip_cb.c:886): assert (!closed) failed
[proxy:0:1@n004.cluster.com] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:1@n004.cluster.com] main (./pm/pmiserv/pmip.c:206): demux engine error waiting for event
[proxy:0:2@n005.cluster.com] HYD_pmcd_pmip_control_cmd_cb (./pm/pmiserv/pmip_cb.c:886): assert (!closed) failed
[proxy:0:2@n005.cluster.com] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:2@n005.cluster.com] main (./pm/pmiserv/pmip.c:206): demux engine error waiting for event
[proxy:0:4@n007.cluster.com] HYD_pmcd_pmip_control_cmd_cb (./pm/pmiserv/pmip_cb.c:886): assert (!closed) failed
[proxy:0:4@n007.cluster.com] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:4@n007.cluster.com] main (./pm/pmiserv/pmip.c:206): demux engine error waiting for event
[mpiexec@n003.cluster.com] HYDT_bscu_wait_for_completion (./tools/bootstrap/utils/bscu_wait.c:76): one of the processes terminated badly; aborting
[mpiexec@n003.cluster.com] HYDT_bsci_wait_for_completion (./tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[mpiexec@n003.cluster.com] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:217): launcher returned error waiting for completion
[mpiexec@n003.cluster.com] main (./ui/mpich/mpiexec.c:330): process manager error waiting for completion
```

@paulromano any ideas what might cause such a segmentation fault? Do you happen to have access to good debugging tools that can be easily deployed on a cluster?

**Comment by wbinventor** [comment]
I'll add that the segmentation fault does not arise when this problem is run with 1,000,000 instead of 10,000,000 particles / batch.

**Comment by paulromano** [comment]
@wbinventor Sorry for the delayed response on this issue. You wouldn't happen to have any statepoints would you? It would be nice if you could re-run and get a statepoint after batch 8. From there, we'll have to try to narrow it down to a specific particle and see what's going on. Are you using threading or just MPI?

**Comment by wbinventor** [comment]
Absolutely, I'll submit a job to generate statepoint files with the latest version from "develop" now.

**Comment by wbinventor** [comment]
Well this segfault doesn't show up for the latest version of the code. I'll close this issue for now, but since I've run into similar segfaults I imagine that I may have to re-open it in the future if I happen across the right random number stream.

**Comment by paulromano** [comment]
That's weird -- don't see what would have changed this bug, but anyhow these things can indeed be very difficult to track down. Happy to assist if you run into it again.

**Comment by wbinventor** [comment]
I spoke too soon! This problem now segfaults after ~620,000,000 instead of the previous measly 80,000,000 histories. I'm re-running to capture the statepoint at 62 batches in case you have the parallel debugging tools to track this one down @paulromano.

**Comment by wbinventor** [comment]
Update: My job on nsecluster has been trying to restart from a statepoint for over 8 hours. The statepoints for this problem are several GB and I'm running on 5 nodes with 12 MPI procs each. OpenMC was compiled with parallel HDF5 v1.8.10 with ifort. @paulromano do you know of any peformance bottlenecks for our statepoint restart? I'll re-run this problem from scratch in order to capture the statepoint at 62 batches, but it may be necessary to improve our I/O in order to debug this segfault

**Comment by wbinventor** [comment]
The input and output files, including "summary.h5" and "statepoint.062.h5" for this problem are in [this](https://www.dropbox.com/sh/zeagygq18unmzk8/AAAd9NUz98_c0IzSEtbpp_H9a?dl=0) Dropbox folder.

**Comment by smharper** [comment]
@wbinventor, while I was tracking down the bug in #584, I also ran into the problem of not being able to restart from statepoint in parallel.  It worked fine with a single processor, but if failed with two.  My recommendation for debugging this issue is to add a line to `transport` that writes out the particle id, restart from your statepoint in serial so you can figure out exactly which particle you fail on.  Then, you can change `transport` again so that it ignores any particles without that id, and you'll be able to re-run your problem particle pretty quickly even though you're in serial.

**Comment by paulromano** [comment]
@wbinventor Can you see if the bugfix from #588 that was just merged fixes your problem?

**Comment by wbinventor** [comment]
Yes, I was thinking the same thing. I'll keep you posted!

**Comment by wbinventor** [comment]
It looks like #588 fixed this issue! Very nice sleuthing @paulromano!
