### ISSUE TITLE
Support for gfortran versions

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#562]
Currently we support building OpenMC with gfortran 4.6+, mostly because Travis CI by default uses Ubuntu 12.04 VMs which in turn have gcc 4.6 by default. That being said, there is a desire among developers (@smharper, @nelsonag, I'm sure you agree) to only support 4.8+ since there is a more complete implementation of the F2003 standard in 4.8. We've also come across a number of weird gfortran-4.6 specific bugs over time.

It appears that Travis is now supporting a new "[trusty](https://docs.travis-ci.com/user/trusty-ci-environment/)" infrastructure based on Ubuntu 14.04 LTS. Unfortunately, this new infrastructure does not support caching for public repositories, so it would increase our build times by about 20 minutes (to install MPICH, HDF5, PHDF5). We could use MPICH or OpenMPI out of the APT repositories which would definitely help, but HDF5 from APT in 14.04 does not support the F2003 HDF5 API so we'd still have to build that from scratch. Alternatively, we could use the ubuntu-toolchain-r/test PPA to install gcc 4.8 on the container-based infrastructure we're currently using.

**Comment by smharper** [comment]
Do you expect they will eventually release the capability to use trusty and caching together?  I wouldn't mind waiting a few months for that.

**Comment by paulromano** [comment]
According to travis-ci/travis-ci#4997, "We have this on our direct roadmap but I don't have an ETA".

**Comment by smharper** [comment]
An extra ~20 minutes on build time sounds kind of painful.  Especially since I am now shamelessly relying on Travis to handle much of my testing.  Based on that, I'm more in favor of the ubuntu-toolchain-r/test route.

**Comment by wbinventor** [comment]
I just set up Travis for OpenMOC and am using the ubuntu-toolchain-r/test PPA for gcc-4.8. Seems like a good short-term workaround. I'm still a Travis n00b and am not one of those developers chomping at the bit to make use of Fortran 2003, but thought I'd drop my support for this path forward.

**Comment by nelsonag** [comment]
Now that I see this exists..... yes I want it! 
@paulromano does your PPA include compiled versions of MPICH, HDF5 with the configurations we would need?  Could you just pull that in in the travis.yaml file if we were to switch to 14.04?

**Comment by paulromano** [comment]
My PPA only includes OpenMC binaries (compiled with OpenMP but no MPI), so unfortunately it won't be a solution for our dependency woes.

**Comment by paulromano** [comment]
Looks like [trusty infrastructure now supports caching](https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone)!

**Comment by nelsonag** [comment]
@paulromano FYI I've got a branch right now which uses trusty.  The Travis build has just started, I'll let you know of the success.  I'm going to basically see if the tests pass and then re-run and try and observe if it is using the caching.  Is there anything else I should look for before putting in this 2-line PR?

**Comment by nelsonag** [comment]
Yeah, the above works fine.  Caching works, and I've also removed the most obvious (per comments) Gfortran 4.6-specific code workaround.

**Comment by nelsonag** [comment]
Closed by #735
