### ISSUE TITLE
BUg when trying to score MT=18

### ISSUE THREAD

**Issue by khurrumsaleem** [mit-crpg/openmc#574]
Hello everyone,

I wanted to report a problem i ran into. For any geometry, if i try to score fission by its ID i.e. 18, the program errors out after the execution of inactive batches. If I use <scores>fission</scores>, then the simulation runs fine. 

I have pasted here the tally which i am using and the output of OpenMC after inactive cycles. 
  <tally id="1">

    <filter type="mesh" bins="1" />
    <filter type="energy" bins="0. 4.e-6 20.0" />
    <nuclides>U-235</nuclides>
    <scores>18</scores>
  </tally>
         

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Backtrace for this error:

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  #0  #0  0x7F2B76629777
0x7F24C513D777
#1  0x7F2B76629D7E
0x#2  0x7F2B75921D3F
7F2B76629777
#1  #1  0x0x7F2B76629D7E
#2  0x7F2B75921D3F
7F24C513DD7E
#2  0x7F24C4435D3F
#0  0x7F24C513D777#0  #0  0x7F24C513D777
#1  0x7F24C513DD7E
#2  0x7F24C4435D3F
#0  0x7F24C513D777
#1  0x0x7F2B766297777F24C513DD7E
#2  

0x7F24C4435D3F
#1  0x7F2B76629D7E
#2  0x7F2B75921D3F
#1  0x7F24C513DD7E
#2  0x7F24C4435D3F
#0  0x7F2B76629777
#1  0x7F2B76629D7E
#2  0x7F2B75921D3F
#3  #3  0x0x4B8B0B4B8B0B in  in __tally_MOD_score_general__tally_MOD_score_general

#4  0x4B4B94 in __tally_MOD_score_tl_on_mesh
#4  0x4B4B94 in __tally_MOD_score_tl_on_mesh
#5  0x4B4D28 in __tally_MOD_score_tracklength_tally
#5  0x4B4D28 in __tally_MOD_score_tracklength_tally
#6  0x46437C in __tracking_MOD_transport
#6  0x46437C in __tracking_MOD_transport
#7  0x49C448 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:?
#8  0x7F2B75ECE349
#9  0x7F2B74924181
#10  0x7F2B759E547C
#7  0x49C448 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:?
#11  0xFFFFFFFFFFFFFFFF
#3  0x4B8B0B in __tally_MOD_score_general
#4  0x4B4B94 in __tally_MOD_score_tl_on_mesh
#5  0x4B4D28 in __tally_MOD_score_tracklength_tally
#6  0x46437C in __tracking_MOD_transport
#7  0x49C448 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:?
#8  0x49C06A in __simulation_MOD_run_simulation
#8  0x49C06A in __simulation_MOD_run_simulation
#9  0x4AD6CE in MAIN__ at main.F90:?
#3  0x4B8B0B in __tally_MOD_score_general
#9  0x4AD6CE in MAIN__ at main.F90:?
#4  0x4B4B94 in __tally_MOD_score_tl_on_mesh
#3  0x4B8B0B in __tally_MOD_score_general
#5  0x4B4D28 in __tally_MOD_score_tracklength_tally
#6  0x46437C in #4  __tracking_MOD_transport
0x4B4B94 in __tally_MOD_score_tl_on_mesh
#7  0x49C448 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:?
#5  0x4B4D28 in __tally_MOD_score_tracklength_tally
#6  0x46437C in __tracking_MOD_transport
#3  0x4B8B0B in __tally_MOD_score_general
#7  0x49C448 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:?
#4  0x4B4B94 in __tally_MOD_score_tl_on_mesh
#8  #5  0x4B4D28 in __tally_MOD_score_tracklength_tally
0x7F24C49E2349#8  0x7F24C49E2349

#6  0x46437C in __tracking_MOD_transport
#9  0x7F24C3438181
#10  0x#3  0x4B8B0B in __tally_MOD_score_general
#9  0x7F24C3438181
#7  0x49C448 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:?
#10  0x7F24C44F947C
#4  0x4B4B94 in __tally_MOD_score_tl_on_mesh
#11  0xFFFFFFFFFFFFFFFF#8  
0x7F24C49E2349
#5  0x4B4D28 in __tally_MOD_score_tracklength_tally
#9  0x7F24C3438181
7F24C44F947C
#10  0x7F24C44F947C
#11  0xFFFFFFFFFFFFFFFF
#11  0xFFFFFFFFFFFFFFFF
#3  #6  0x0x4B8B0B46437C in  in __tally_MOD_score_general__tracking_MOD_transport

#7  0x49C448 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:?
#4  0x4B4B94 in __tally_MOD_score_tl_on_mesh
#8  0x7F2B75ECE349
#5  #9  0x0x4B4D287F2B74924181 in 
__tally_MOD_score_tracklength_tally
#10  #6  0x7F2B759E547C
0x46437C in __tracking_MOD_transport
#11  0xFFFFFFFFFFFFFFFF
#7  0x49C448 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:?
#8  0x7F2B75ECE349
#9  0x7F2B74924181
#10  0x7F2B759E547C
#11  0xFFFFFFFFFFFFFFFF

**Comment by paulromano** [comment]
I tried to reproduce the segfault you're getting but was unable to. Can you recompile turning debug flags on (cmake -Ddebug=on) and then re-run? That will allow us to narrow it down to a specific line of code.

**Comment by khurrumsaleem** [comment]
Hi @paulromano 

i have recompiled the code by cmake -Ddebug=on and got the following error message. 

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7F2B483FE777
#0  0x7F2B483FE777
#1  0x7F2B483FED7E
#1  0x7F2B483FED7E
#2  0x7F2B476F6D3F
#2  0x7F2B476F6D3F
#3  #3  0x5331BC in __tally_MOD_score_general at tally.F90:707
#0  0x7F2B483FE777
#1  0x7F2B483FED7E
#4  0x528C9B in __tally_MOD_score_tl_on_mesh at tally.F90:1575 (discriminator 2)
#2  0x7F2B476F6D3F
#5  0x528EA5 in __tally_MOD_score_tracklength_tally at tally.F90:1230
#6  0x48A4EC in __tracking_MOD_transport at tracking.F90:109
#7  0x4EDD69 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:91 (discriminator 1)
#8  0x4ED581 in __simulation_MOD_run_simulation at simulation.F90:83
#9  0x513229 in MAIN__ at main.F90:19
#3  0x5331BC in __tally_MOD_score_general at tally.F90:707
#4  0x528C9B in __tally_MOD_score_tl_on_mesh at tally.F90:1575 (discriminator 2)
#5  0x528EA5 in __tally_MOD_score_tracklength_tally at tally.F90:1230
#6  0x48A4EC in __tracking_MOD_transport at tracking.F90:109
#7  0x4EDD69 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:91 (discriminator 1)
#8  0x7F2B47CA3349
#9  0x7F2B466F9181
#10  0x7F2B477BA47C
#11  0xFFFFFFFFFFFFFFFF
#0  #0  0x7F78F3754777
#1  0x7F78F3754D7E
#2  0x7F78F2A4CD3F
0x7F2B483FE777
#1  0x7F2B483FED7E
#2  0x7F2B476F6D3F
#0  0x7F78F3754777
#1  0x7F78F3754D7E
#2  0x7F78F2A4CD3F
#3  0x5331BC in __tally_MOD_score_general at tally.F90:707
#4  0x528C9B in __tally_MOD_score_tl_on_mesh at tally.F90:1575 (discriminator 2)
#5  0x528EA5 in __tally_MOD_score_tracklength_tally at tally.F90:1230
#6  0x48A4EC in __tracking_MOD_transport at tracking.F90:109
#7  0x4EDD69 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:91 (discriminator 1)
#8  0x7F78F2FF9349
#9  0x7F78F1A4F181
#10  0x7F78F2B1047C
#11  0xFFFFFFFFFFFFFFFF
0x5331BC in __tally_MOD_score_general at tally.F90:707
#4  0x528C9B in __tally_MOD_score_tl_on_mesh at tally.F90:1575 (discriminator 2)
#5  0x528EA5 in __tally_MOD_score_tracklength_tally at tally.F90:1230
#6  0x48A4EC in __tracking_MOD_transport at tracking.F90:109
#7  0x4EDD69 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:91 (discriminator 1)
#8  0x7F2B47CA3349
#9  0x7F2B466F9181
#10  0x7F2B477BA47C
#11  0xFFFFFFFFFFFFFFFF
#3  0x5331BC in __tally_MOD_score_general at tally.F90:707
#4  0x528C9B in __tally_MOD_score_tl_on_mesh at tally.F90:1575 (discriminator 2)
#5  0x528EA5 in __tally_MOD_score_tracklength_tally at tally.F90:1230
#6  0x48A4EC in __tracking_MOD_transport at tracking.F90:109
#7  0x4EDD69 in __simulation_MOD_run_simulation._omp_fn.2 at simulation.F90:91 (discriminator 1)
#8  0x7F78F2FF9349
#9  0x7F78F1A4F181
#10  0x7F78F2B1047C
#11  0xFFFFFFFFFFFFFFFF

**Comment by paulromano** [comment]
@khurrumsaleem This issue should be fixed now on the develop branch.

**Comment by khurrumsaleem** [comment]
Thanks @paulromano
