### ISSUE TITLE
can't  make  html  error

### ISSUE THREAD

**Issue by Aguomath** [mit-crpg/openmc#581]
Could anyone help me ? When I make the html manual, it appears the error :Could not import extension sphinx.ext.napoleon (exception: No module named napoleon). Thanks !

**Comment by paulromano** [comment]
To build the documentation, you need [Sphinx](http://www.sphinx-doc.org/en/stable/index.html) version 1.3 or higher. Prior to version 1.3, the napoleon extension (which is used to process NumPy-style docstrings) was not included in Sphinx itself but instead had to be installed separately.

**Comment by Aguomath** [comment]
Thank you.
