### ISSUE TITLE
Update MGXS Module of Python API To Support Data Used by Multi-Group Mode

### ISSUE THREAD

**Issue by nelsonag** [mit-crpg/openmc#597]
The multi-group capability in OpenMC (OpenMG, if you will) can take advantage of different data than is currently provided by the MGXS and MGXSLibrary Python APIs.  This includes the following items which are very likely to be needed by users:
- [x] scatter moment matrices (i.e., moment as in Legendre moments) [Edit: closed in #644]
- [x] nu-scatter moment matrices [Edit: closed in #644]

And the following items which are lower-need since many users wont use this feature, but OpenMC still supports the functionality and therefore would be useful to have:
- [x] polar and azimuthal angle dependent cross sections generated with constant width bins unique to each dimension (polar and azimuthal) (this applies for all current data in the develop branch and this issue, save for the scattering multiplication matrix, as that's overkill).
- [x] scattering matrices with change-in-angle information provided in equal-width mu bins.
- [x] nu-scattering matrices with change-in-angle information provided in equal-width mu bins.
- [x] nu-fission matrix
- [x] scattering multiplication matrix (i.e., nu-scatter-0[g'->g]/scatter-0[g'->g] used to multiply particle weights after a scattering event.

**Comment by nelsonag** [comment]
Closed by #644, #653, #758, and #778

We now have a MGXS API that is fully integrated with the MG Mode! Yay!

**Comment by wbinventor** [comment]
Whew, you made all of this happen @nelsonag! Nicely done sir, nicely done.

**Comment by nelsonag** [comment]
with lots of help from you and the great MGXS API!!
