### ISSUE TITLE
Implement some form of 'sparse array' treatment for scattering matrices in multi-group mode

### ISSUE THREAD

**Issue by nelsonag** [mit-crpg/openmc#602]
Right now the entire GxG scattering matrix is stored and used during the sampling of outgoing energies for multi-group scattering.  Physically speaking, this matrix should be closer to a lower triangular matrix with some sparsity even below the diagonal.  A simple but likely quite effective way to treat this is to simply include g_out_min and g_out_max for every g_in of the matrix and then simply not store or check entries below g_out_min and above g_out_max.

**Comment by nelsonag** [comment]
I had some example figures so I might as well include them.  Here are water and fuel P0 matrices for a pincell model.  

![scatt_mat](https://cloud.githubusercontent.com/assets/1037107/13464598/e0d053b0-e05f-11e5-9021-32107df7d95b.png)

**Comment by mellis13** [comment]
@nelsonag I really like these plots -- do you have the energy bounds of the groups handy?

**Comment by nelsonag** [comment]
Sure!  I probably wont be able to get to it until later tonight, if you'd like it before then, you can find it in the HELIOS manual as this is the 47-group structure discussed there.

**Comment by nelsonag** [comment]
Nevermind, had access from here
![47g](https://cloud.githubusercontent.com/assets/1037107/13468918/0d3b714c-e073-11e5-91a2-fb9f3ac73eaa.png)
:

**Comment by mellis13** [comment]
Thanks!

**Comment by paulromano** [comment]
Closed with the merging of #611
