### ISSUE TITLE
Check 'cmfd.xml' correctly

### ISSUE THREAD

**Issue by liangjg** [mit-crpg/openmc#605]
The code crashes when `run_cmfd` is `on` but no `cmfd.xml` file exists, because the variable used for judgement is misused:

``` fortran
    if (.not. file_exists) then
      ! CMFD is optional unless it is in on from settings
      if (cmfd_on) then
        call fatal_error("No CMFD XML file, '" // trim(filename) // "' does not&
             & exist!")
      end if
      return
```
The `cmfd_on` (line 73 in `cmfd_input.F90`) should be `cmfd_run`. `cmfd_run` is the input parameter while `cmfd_on` is initialized after reading  `cmfd.xml`.

**Comment by paulromano** [comment]
@liangjg Do you want to submit a pull request fixing this?

**Comment by liangjg** [comment]
Sure. I created the issue because I had though it may be too small to be a PR.
