### ISSUE TITLE
Major Shift in Eigenvalue in CE Mode Related to #494

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/openmc#608]
I've been baffled recently by a major shift in the eigenvalue  (-4000pcm) computed by OpenMC for a few of the geometries I commonly simulate. I finally took some time to track this down and to my surprise, it appears to be related to the introduction of the multi-group mode in #494. The geometries for which I've observed this effect are composed of multiple assemblies from the BEAVRS benchmark. I've illustrated one example below with 2x2 assemblies next to a water reflector, with reflective BCs on the bottom and left, above and below, and vacuum on the right and bottom:

<img src="https://cloud.githubusercontent.com/assets/209492/13674451/84b2f626-e6ab-11e5-84b3-68395c097c0f.png"  width="200">

Using the *same* XML input files I observe the following eigenvalues when run with the following two commits before and after the multi-group mode merge:

**OpenMC Eigenvalues**
0.95915 +/- 0.00099 (SHA before: 713f6bf0fb6e207d315b42a485abed8bc66c8815)
0.92086 +/- 0.00092 (SHA after: 446262f709c934c59a17792da71b66bc06d611d9)

This issue came up since the eigenvalues I computed by OpenMOC (on a coarse spatial and angular mesh, but the trend is still the same) from 2-group MGXS in each case remain about the same:

**OpenMOC Eigenvalues**
0.962293 (SHA before: 713f6bf0fb6e207d315b42a485abed8bc66c8815)
0.958277 (SHA after: 446262f709c934c59a17792da71b66bc06d611d9)

Note that I only ran 100 batches of 10,000 particles/batch for the results cited here. I've confirmed these results with more particles/batch such that the two OpenMOC eigenvalues converge to one another, but OpenMC's eigenvalues remain shifted by ~4000 pcm.

I didn't review #494 in much detail and have no idea why it caused the eigenvalue to change so much for this model (and others). @nelsonag @paulromano @smharper @samuelshaner any ideas?

The XML input files for this case are in [this](https://www.dropbox.com/sh/l4l3c8v6iheb6z1/AABrmaHvpxbp4lEvomi1PFnia?dl=0) dropbox folder. Note that the "tallies.xml" file is for a distribcell nuclide-by-nuclide MGXS library with 70-groups which will easily consume your memory, but it is not needed to reproduce this issue.

**Comment by wbinventor** [comment]
By the way, I've observed this same issue for a similar geometry with only the 2x2 assemblies and without the reflector.

**Comment by smharper** [comment]
Woah!  That's not good.  I'm quite confused though.  #494 didn't modify the CE tests.  (For anyone struggling like me to figure out what files were changed, you can use this:)
```
git diff 713f6bf0fb6e207d315b42a485abed8bc66c8815 446262f709c934c59a17792da71b66bc06d611d9 --name-only
```

**Comment by wbinventor** [comment]
Yes, I know! I was hesitant to open this issue for that very reason, but I
did enough homework to convince myself that this issue appeared since that
PR. As for the tests, H-M is a much simpler model than BEAVRS, so I don't
think we can necessarily trust that we can catch all possible issues
(though one would hope...).

**Comment by nelsonag** [comment]
Sigh.  Nothing obvious stands out at the moment, and this should not be happening.   Whatever it is, sorry about that.  I cant invest any time in to it until tonight of course, but hopefully will get some PR together in short order.

**Comment by wbinventor** [comment]
Should we expect the results in CE mode to change at all with the inclusion
of MG? In other words, should I not only be surprised that the eigenvalue
dramatically changed, but also that the tallies I use to compute MGXS also
changed?

**Comment by nelsonag** [comment]
No, you should not expect this.  After a quick look, the only feature in your input I don't remember having in any of my own models is the iso-in-lab option.  I also don't see a test for that, so it is possible I could have screwed that up somehow and was none the wiser.  I am not confident enough to put money down on this, but does the problem persist without this option enabled?

**Comment by wbinventor** [comment]
@nelsonag you hit the nail on the head - when I remove the "iso-in-lab" tag for the code prior to your MG PR the eigenvalue and tallies are exactly the same. In other words, the MG mode simply broke the "iso-in-lab" option and we never knew about it since it wasn't included in the test suite. Fortunately, this probably hasn't impacted anyone other than me since I doubt anyone is using this mode unless they are really interested in studying biases induced by MGXS approximations.

Any idea why the "iso-in-lab" option is now ignored? I definitely agree that we should add a test of this feature to the suite once we resolve this issue.

**Comment by nelsonag** [comment]
@wbinventor I haven't the vaguest idea why that would of broke.  I'll blame git ;-).  Getting to a fix very shortly.

**Comment by nelsonag** [comment]
Alright, that was it.  Sorry about this one folks.  The block of code which performs the iso-in-lab check in from the input was hanging out with the code that checks the <macroscopic> element instead of the <nuclide> element.  I've put that block back in its place.  

Here are the results for the problem above:
current develop branch: keff = 0.92086+/-0.00092 
the code I am about to submit: 0.95966 +/-  0.00094 (I guess after the URR sampling change this week a minor, statistically insignificant, deviation from the commit used above is to be expected)

**Comment by wbinventor** [comment]
Closed with #609. I'll open a PR with a new test of the "iso-in-lab" feature shortly.

**Comment by paulromano** [comment]
Thanks @wbinventor and @nelsonag! Happy to sit back and watch the action...

**Comment by nelsonag** [comment]
Not a problem @wbinventor and @paulromano; sorry for the kerfuffle.

**Comment by wbinventor** [comment]
Now we all know to start our issues off with the word "Major ..." if we want a quick turnaround, even if (as this case turned out to be) it is a kerfuffle specific to our own use case :-) But in all seriousness, thanks for the help with this @nelsonag.
