### ISSUE TITLE
Combined k-effective estimator producing NaN variance

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#613]
Apparently it is possible to get a NaN for the variance of the combined k-effective estimator. I know that the MC21 folks ran into this issue at one point and I helped get it fixed, and now for the life of me I can't remember what exactly the culprit was. It seems to happen when you have _a lot_ of particles. I saw it when running a case with 78 billion histories. Side note: this run used all 786432 cores on the ANL Mira supercomputer, as far as I know the biggest OpenMC run ever!

**Comment by nelsonag** [comment]
First of all, awesome!
Second of all, I can get it in multi-group mode with survival biasing.  In that case, the collision estimator and analog estimator are the same thing, and our algorithm for computing the combined keff NaNs out in that case.  I've been playing around with ways to beat it, but have not gotten anywhere.

**Comment by nelsonag** [comment]
But hey, there is some good news out of this PR, besides the massive core
count: I now remember what that issue was I couldn't remember! And this is
it!

**Comment by paulromano** [comment]
Fixed in #792
