### ISSUE TITLE
need guid about tallies file

### ISSUE THREAD

**Issue by iqranoreen** [mit-crpg/openmc#614]
I am new user of openmc and getting difficulties in making tallies.xml file.
I have a fix source of 14Mev energy. source strength is 10e9. I made 4 cells and 3 surfaces. I want to calculate surface flux and current across surfaces 1, 2 and neutron flux across surfaces 1,2,3. how to write tally file please guide me what is wrong.
if I write
<?xml version="1.0"?>
<tallies>

  <tally id="1" scores="flux"/>
  <filter type="surface" bins="1 2" />
<filter type="energy" bins="0.20" />

<tally id="2">
    <filter type="mesh" bins="2" />
    <scores>current</scores>
</tally>
  <mesh id="1" type="regular">
    <lower_left>-300 -300 -300</lower_left>
    <upper_right>300 300 300</upper_right>
    <dimension>1 1 1</dimension>
</mesh>
  <mesh id="2" type="regular">
    <lower_left>-370 -370 -370</lower_left>
    <upper_right>370 370 370</upper_right>
    <dimension>1 1 1</dimension>
</mesh>
<tally id="3" scores="nu-fission" />
<filter type="surface" bins="1 2 3" />
 
</tallies>
then result of nu-fission rate is zero by openmc.

if I write
<tally id="1">
  <filter type="surface" bins="1 2" />
 <scores>flux<scores>
<tally />
then openmc says surface filter is not supported.
please guid me how can I get desired results.
Thanks in advance.

**Comment by paulromano** [comment]
Currently OpenMC only supports volumetric tallies with the one exception of surface current tallies on a mesh. I'll be sure to post a message to the user's group in the future should we add support for surface flux and surface current tallies.
