### ISSUE TITLE
Confusing documentation for generated microscopic cross sections

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#617]
The docstring for `openmc.mgxs.MGXS` seems to indicate that one can specify the "nuclides" attribute to limit what nuclides you get cross sections for (it lists it in parameters and attributes). For one, there is no nuclides argument on `__init__()`, and there is no nuclides setter. If a user sets it explicitly, it just causes things to break on the back-end; the tally is created with all nuclides in the material, and then when post-processing `load_from_statepoint()` will expect a different number of bins. Is there anything preventing us from making used-specified nuclides for MGXS available? Either we should make it available or prevent a user like myself from explicitly setting nuclides.

**Comment by wbinventor** [comment]
Thanks for raising this issue @paulromano. Sorry you ran into it in the first place. I've actually not used the custom nuclide option - or at least not in a long while which is likely why this bug crept in. Hopefully the fix in #619 solves the issue. The documentation does seem a bit clunky to read. I'm happy to update that as well (sometime early next week), though I tend to believe that a user with a few more degrees of separation can write better documentation than the original developer.

**Comment by wbinventor** [comment]
I'm glad this fix worked for you @paulromano! The docstring has been updated - take a look and let me know if it is more clear now.

**Comment by paulromano** [comment]
Closed with the merging of #619
