### ISSUE TITLE
Surface current with 2D mesh fails

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#63]
When you try to do a surface current tally with a 2D mesh, the following error is displayed:

    Creating unionized energy grid...
    forrtl: severe (41): insufficient virtual memory
    Image              PC                Routine            Line        Source             
    openmc             0000000000506D2A  Unknown               Unknown  Unknown
    openmc             0000000000505826  Unknown               Unknown  Unknown
    openmc             00000000004BA730  Unknown               Unknown  Unknown
    openmc             0000000000474AAE  Unknown               Unknown  Unknown
    openmc             00000000004A2216  Unknown               Unknown  Unknown
    openmc             00000000004389A4  Unknown               Unknown  Unknown
    openmc             000000000041A2EA  Unknown               Unknown  Unknown
    openmc             0000000000422F67  Unknown               Unknown  Unknown
    openmc             00000000004032FC  Unknown               Unknown  Unknown
    libc.so.6          00007FB07262D30D  Unknown               Unknown  Unknown
    openmc             00000000004031F9  Unknown               Unknown  Unknown

**Comment by samuelshaner** [comment]
Fixed in PR #717
