### ISSUE TITLE
A few proposed changes to Python API

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#630]
I'd like to propose that:

1. We get rid of the `GeometryFile` class and instead just put an `export_to_xml()` method on `Geometry` directly. This would better match how we handle materials and settings and remove one level of indirection (thereby making our boilerplate code a little shorter).
2. The methods of `Executor` become regular functions since `Executor` doesn't really carry any state with it. We could just have functions `openmc.run()` and `openmc.plot()`.
3. Rename the `Surface.coeffs` attribute to `Surface.coefficients`.
4. Rename the `SettingsFile` class to simply `Settings`.

@wbinventor (and others): what do you think?

**Comment by wbinventor** [comment]
@paulromano - first, i'm a fan of proposals 2 and 3. As for 1, minimizing boilerplate code is always a good thing in my book. But my only concern is that the XML file generation may appear fragmented to those (most?) users who are still writing XML by hand. This same concern applies to proposal 4 as well. Perhaps if we doove away from `GeometryFile` and `SettingsFile` we should do the same for `MaterialsFile` and `PlotsFile` by renaming them to `Materials` and `Plots`. My inclination would be to leave the naming convention to ease the mental transition for everyone still on the XML bandwagon.

**Comment by wbinventor** [comment]
@paulromano - first, I'm a fan of proposals 2 and 3. As for 1, minimizing boilerplate code is always a good thing in my book. But my only concern is that the XML file generation may appear fragmented to those (most?) users who are still writing XML by hand. This same concern applies to proposal 4 as well. Perhaps if we move away from `GeometryFile` and `SettingsFile` we should do the same for `MaterialsFile` and `PlotsFile` by renaming them to `Materials` and `Plots`. My inclination would be to leave the naming convention to ease the mental transition for everyone still on the XML bandwagon.

**Comment by paulromano** [comment]
Hmm, I do agree that makes it a bit fragmented with `MaterialsFile` and `PlotsFile` still around. I like the idea of moving to `Geometry`, `Materials`, `Settings`, and `Plots`. While I can sympathize with the XML to Python mental transition pains, my opinion is that if we ever want to rename classes to what we think they really should be, now is the time before everyone starts using the API (will be a lot more painful further down the road). I think leaving out "File" in the class names better matches the abstraction -- there's nothing inherent in the class definitions that makes them files; it just so happens that they have an equivalent XML representation.

**Comment by wbinventor** [comment]
Yeah I agree that sooner is better than later. :+1 to moving away from the `*File` paradigm entirely.
