### ISSUE TITLE
Low energy neutrons

### ISSUE THREAD

**Issue by smharper** [mit-crpg/openmc#652]
I've discovered a potential problem with the way we compute cross sections for low-energy neutrons.  Currently, if a neutron is below the lowest energy grid point, we assign it to the first grid.  In cross_section.F90:
```f90
if (E <= nuc % energy(1)) then
  i_grid = 1
```

We then interpolate between the first two grid points
```f90
f = (E - nuc%energy(i_grid))/(nuc%energy(i_grid+1) - nuc%energy(i_grid))
```
which will give a negative value of `f` for `E < nuc % energy(1)`.  Essentially, this will cause us to extrapolate down from the first two grid points.

The correct way to handle these low energies is not obvious, but extrapolating feels like a bad idea.  It might give us negative cross sections, for example.  I do encounter energy values this low relatively frequently, about one per billion particles in my BEAVRS pincells.

What do you guys think?  Is extrapolating fine?  Maybe we should pin particles to the minimum energy given by our cross sections?  They are infrequent enough that we could also probably kill the particle without hurting results.

**Comment by nelsonag** [comment]
Given the smoothly varying shape of cross sections very far in to the
thermal range, extrapolating below the first point always seemed like a
decent approach to me since the cross sections are either 1/v or at worst,
constant.  Are there any cross sections at risk for negative cross sections
due to this approach?

**Comment by cjosey** [comment]
Honestly, as long as the method is consistent, it really doesn't matter.  At such energies, the assumption that a neutron is a point starts to break down and there are no "right" answers.  Further, the evaluators typically make no claims about any data below 1e-5 eV.

**Comment by paulromano** [comment]
I think the risk of negative cross sections is very very small, especially with the 1/v Doppler tail. I've certainly never encountered negatives due to this. I tend to agree with @cjosey that whatever we choose probably doesn't matter.

**Comment by nelsonag** [comment]
So should we close this issue then?

**Comment by smharper** [comment]
Sure, I don't think this is going to be a problem.  Was good to think about, anyway.
