### ISSUE TITLE
Possible issue with HDF5 1.10

### ISSUE THREAD

**Issue by cjosey** [mit-crpg/openmc#654]
My computer just updated to rebase everything off of HDF5 1.10. When I run the test suite, basically anything involving tallies fails.  I recompiled forcing 1.8.17 and using Anaconda for my python3 (which still uses 1.8.15 as its basis).  When running this way, none of the tests fail.

As far as I can tell, h5py should support (at least some of the new features of)1.10 as of 2.5.0, and I have 2.6.0 installed.  So, while this may be an upstream issue, just thought I'd bring it to everyone's attention.

**Comment by wbinventor** [comment]
There is a known issue with h5py v2.6 - do you still run into this issue after downgrading to v2.5?

**Comment by paulromano** [comment]
Using h5py v2.6 for sure will fail as @wbinventor mentioned. Downgrade to 2.5 and re-open if you still have problems.

**Comment by cjosey** [comment]
Well, problem solved.  Turns out the known issue in 2.6 is fixed if compiled from source.  Also, h5py 2.5 does not seem to support 1.10 at all, with all tests failing instead of some.

**Comment by nelsonag** [comment]
When you say 2.6 is fixed if compiled from source, do you mean compiling
from the dev branch of 2.6.x, or simply that when you compile the 2.6.0
source, it works?

I can confirm the 2.5 and 1.10 issues.

**Comment by cjosey** [comment]
Ah, I got a bit confused by h5py's git layout.  I thought that since there was a 2.3-2.5 branch, that master was the 2.6 branch.  The commit tagged 2.6 does not work, but master of https://github.com/h5py/h5py works.
