### ISSUE TITLE
Tally Merging not performing correctly

### ISSUE THREAD

**Issue by nelsonag** [mit-crpg/openmc#655]
When using the Python API to generate some problems, I've found that the tally merge process is not fully merging all the tallies that it can.  It seems like every merge call merges one tally with another but no more.  
This behavior can be readily seen by running the MGXS Example notebook iv locally and viewing the continuous-energy tallies.xml file it produces on the back-end.  Even though a merge was requested, there are massive amounts of tallies present in the file with substantial room for further combining.

FYI: As a local temporary workaround I have been calling the merge routine for every domain that I am tallying over.  This seems to work and others should adopt this in the meantime.  

When this is fixed it would also be wise to update the Python API Example notebooks so the OpenMC active neutron calculation rate is not portrayed as significantly lower than what it would be.

**Comment by wbinventor** [comment]
Closed with #665.
