### ISSUE TITLE
Unable to find merged tally when loading tally from statepoint

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/openmc#663]
The addition of the `exact` option in the `StatePoint.get_tally()` method in PR #660 has resulted in the `MGXS.load_from_statepoint()` method producing the following error in `mgxs-part-iii.ipynb`:

    # Initialize MGXS Library with OpenMC statepoint data
    mgxs_lib.load_from_statepoint(sp)

    ---------------------------------------------------------------------------
    LookupError                               Traceback (most recent call last)
    <ipython-input-28-76d7abb36a81> in <module>()
          1 # Initialize MGXS Library with OpenMC statepoint data
    ----> 2 mgxs_lib.load_from_statepoint(sp)
    
    /home/shaner/.local/lib/python2.7/site-packages/openmc-0.7.1-py2.7.egg/openmc/mgxs/library.pyc in load_from_statepoint(self, statepoint)
        446             for mgxs_type in self.mgxs_types:
        447                 mgxs = self.get_mgxs(domain, mgxs_type)
    --> 448                 mgxs.load_from_statepoint(statepoint)
        449                 mgxs.sparse = self.sparse
        450 
    
    /home/shaner/.local/lib/python2.7/site-packages/openmc-0.7.1-py2.7.egg/openmc/mgxs/mgxs.pyc in load_from_statepoint(self, statepoint)
        694             sp_tally = statepoint.get_tally(
        695                 tally.scores, tally.filters, tally.nuclides,
    --> 696                 estimator=tally.estimator, exact=True)
        697             sp_tally = sp_tally.get_slice(
        698                 tally.scores, filters, filter_bins, tally.nuclides)

    /home/shaner/.local/lib/python2.7/site-packages/openmc-0.7.1-py2.7.egg/openmc/statepoint.pyc in get_tally(self, scores, filters, nuclides, name, id, estimator, exact)
        620         # If we did not find the Tally, return an error message
        621         if tally is None:
    --> 622             raise LookupError('Unable to get Tally')
        623 
        624         return tally

    LookupError: Unable to get Tally

If the tallies are not merged, MGXS is able to load the tallies from statepoint just fine. This error seems to occur regardless of the cross sections used in:

    mgxs_lib.mgxs_types = ['transport', 'nu-fission', 'fission', 'nu-scatter matrix', 'chi']

For instance, even if `mgxs_lib.mgxs_types` is set to `['total']`, the error is still thrown. I haven't done too much digging into the cause of the error, but it should be pretty easy to reproduce by running `mgxs-part-iii.ipynb`.

**Comment by wbinventor** [comment]
This issue is my fault for not having done due diligence for #660. If tallies are merged for `MGXS` during input generation, then the `exact` option will not work when retrieving those tallies from a `StatePoint`. For example, if multiple `MGXS` are created for different cells/materials, their cell/material filters will be merged with a single tally having a cell/material filter with multiple bins n the input. However, the `MGXS` will be unable to find their uniquely matching tallies in the `StatePoint` with a cell/material filter with a single bin. I'm not really sure how to address this without re-opening issue #657 and am open to ideas.

**Comment by wbinventor** [comment]
One idea would be to have separate `exact_filters`, `exact_nuclides` and `exact_scores` parameters (in the case of MGXS, we would only set `exact_nuclides` to `True` and `exact_filters` and `exact_scores` would be set to `False). Alternatively, `exact` could accept some iterable of items specifying which paramters should be met exactly (*i.e.*, a dictionary with string keys "filters", "scores", etc. and boolean values).

**Comment by wbinventor** [comment]
With a more consideration, neither of the "solutions" proposed above would actually solve this issue.

**Comment by nelsonag** [comment]
So the bug in #657 was found because scatter-p1 from a scatter matrix tally was a successful match when actually looking for scatter-1 from within transportxs. Are all use cases which could 'excite' this error obviated if the search function doesn't consider scatter-p1 a stand in for scatter-1?

**Comment by wbinventor** [comment]
I'm not sure exactly how to answer your question @nelsonag, but it is worth noting that in the output "statepoint.h5" file there will actually not be *any* "scatter-p1" scores - instead, "scatter-px" scores in the input are expanded into separate "scatter-0", "scatter-1", ... " scatter-x" scores in the output.
