### ISSUE TITLE
Tally score be undefined?

### ISSUE THREAD

**Issue by mjlong** [mit-crpg/openmc#685]
master branch Tally.F90, line 64
`if (p % event /= EVENT_SCATTER) cycle SCORE_LOOP`

When p % event /= EVENT_SCATTER, will the uninitialized variable `score` contribute an undefined value to  `t % results(score_index, filter_index) % value`?

**Comment by paulromano** [comment]
If the event is not scattering, `cycle SCORE_LOOP` just sends control to the top of the do loop and on to the next iteration, so no undefined value would ever be store to `t % results`.
