### ISSUE TITLE
Source distributed over fissionable zones

### ISSUE THREAD

**Issue by tjlaboss** [mit-crpg/openmc#693]
It is possible to create a distributed source using the flag `only_fissionable=True` over zones with no fissionable isotopes in them. In this case, OpenMC currently hangs on `Initializing source particles...` indefinitely.

If enough particles are rejected, it should probably raise an error and alert the user.

**Comment by paulromano** [comment]
Thanks for reporting @tjlaboss! Should be an easy fix.
