### ISSUE TITLE
HDF5 Fortran Errors

### ISSUE THREAD

**Issue by scopatz** [mit-crpg/openmc#727]
Hello All, 

I am trying to build a conda package for OpenMC for conda-forge.  I am running into many errors of the form:

```
[ 71%] Building Fortran object CMakeFiles/openmc.dir/src/angle_distribution.F90.o
/home/scopatz/miniconda/conda-bld/openmc_1475272242147/work/openmc-0.8.0/src/hdf5_interface.F90:2407.60:

      call h5dread_f(dset_id, dtype_real, f_ptr_r, hdf5_err)
                                                            1
Error: There is no specific subroutine for the generic 'h5dread_f' at (1)
```

I am not sure where this is coming from and various flags to fix this (like `-fdefault-integer-8`) then break fox.  

You can find the recipe and the build script I am using here: https://github.com/scopatz/staged-recipes/tree/openmc/recipes/openmc

Can anyone point me inthe right direction here, please? Or maybe better yet, if a core dev of OpenMC wants to take over the recipe that would be even better! I could then help make sure it gets through the conda-forge process.  

Thanks in advance!

**Comment by scopatz** [comment]
Also CC @FlanFlanagan, just so he is aware.

**Comment by nelsonag** [comment]
Any idea if that hdf5 Liv was compiled with Fortran support? (E.g.,
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/hdf5-cpp-fortran
)

**Comment by scopatz** [comment]
Yes, it was.  You can see the script for how was compiled here: https://github.com/conda-forge/hdf5-feedstock/blob/master/recipe/build.sh#L24

**Comment by paulromano** [comment]
If you're using HDF5 < 1.10, you also need to specify `--enable-fortran2003`.

**Comment by scopatz** [comment]
Thanks @paulromano, adding `--enable-fortran2003` to the OpenMC cmake call didn't work and produces the same failures.

**Comment by scopatz** [comment]
Or do you mean to the HDF5 build?

**Comment by paulromano** [comment]
Yes, on the HDF5 build itself.

**Comment by paulromano** [comment]
@scopatz Closing this as I am assuming `--enable-fortran2003` fixed the problems. Feel free to reopen if you experience further build issues.

**Comment by scopatz** [comment]
Hi Paul, I think closing this was premature as I haven't confirmed that f03 was the issue. For whatever reason, it is taking a long time to get the new build of HDF5 approved....

**Comment by paulromano** [comment]
Premature, maybe, but given that we know the prior HDF5 installation didn't have `--enable-fortran2003`, one would expect to get the exact error you received. We've also had a number of users run into the same problem, so my closing the issue was based on it being a known problem with a known resolution. Again, feel free to reopen if you're still having issues after the new build of HDF5 goes through.

**Comment by scopatz** [comment]
I don't have permissions to reopen.

**Comment by paulromano** [comment]
Very well then. I'll reopen and you can close at your leisure :)

**Comment by scopatz** [comment]
Thanks! I have been working on this throughout the weekend, but not everyone does that and so I am not surprised that the update wasn't merged yet.

**Comment by scopatz** [comment]
Ok the new hdf5 package does seem to work.  Thanks @nelsonag @paulromano
