### ISSUE TITLE
get_nndc_data.py not installed to $PREFIX/bin

### ISSUE THREAD

**Issue by scopatz** [mit-crpg/openmc#731]
This script seems like it is something that users and developers alike would wish to use. However, it is not part of the installation and is missed by `conda build` as a result.  While the conda recipe or the apt package could forcibly push this file into the package, it seems like would be best if this file (and related files) was actually copied over by cmake.

Right now users have to install openmc and then separately go get this file from the source repository.

**Comment by paulromano** [comment]
This thought crossed my mind -- you're absolutely right, it really belongs in scripts. Thanks for bringing it up!

**Comment by scopatz** [comment]
No problem! Glad it isn't totally out of bounds :)

**Comment by paulromano** [comment]
Closed by #733
