### ISSUE TITLE
String version info for our HDF5 format

### ISSUE THREAD

**Issue by smharper** [mit-crpg/openmc#766]
Our HDF5 data has a `version` attribute made of 2 integers for major and minor numbers.  I propose that we use a string instead because it is much more flexible.  Maybe someday in the future we'll suddenly acquire the need for another minor number like `v3.4.1`, or beta numbers like `v2.1b2`, or some other weird versioning information that we can't predict now.

Do you all agree?

**Comment by wbinventor** [comment]
I'm neutral - I don't see any problem, though I'm also not sure I see the real upside of making this move now when there isn't (yet) a need.

**Comment by nelsonag** [comment]
While I agree there probably isn't a need yet, if we think the flexibility
is warranted now is the time to adjust.  That way we never have to carry
around code that checks for both a string and 2 integer version number.  If
we do it now we'd only have to carry around code to check just one.

**Comment by paulromano** [comment]
I agree that if we are making a change, let's do it now. That being said, I don't see much value added in going to a string. My thought on the versioning for data is that it should essentially follow semantic versioning: increase the major version when incompatible changes are made and increase the minor version when backwards-compatible changes are made (e.g., addition of new data that doesn't affect existing). The normal "patch" version number would be used for bug-fixes, but IMO while it makes sense for software, it doesn't really apply to a *format*. If there's a bug in the format, you'd need to change it in a presumably incompatible manner. So, I can't really imagine any situation in which we'd need a third version number, and applying "alpha" or "beta" suffixes doesn't make sense to me either.

**Comment by paulromano** [comment]
Also, as a point of reference, our output formats use only a single version number right now.

**Comment by paulromano** [comment]
Closed with #794
