### ISSUE TITLE
Creation of example notebooks showcasing non-obvious capabilities of MG mode

### ISSUE THREAD

**Issue by nelsonag** [mit-crpg/openmc#791]
As pointed out by @wbinventor in #787, example notebooks are needed to showcase capabilities of MG-mode that are not very standard.  This series would likely be in a new 'chapter' of example notebooks.  Information I expect to include in the notebooks are:

- [x] Start basic, calculating C5G7 or some other similar LWR-type problem with an existing MGXS dataset.  This case will not use anything advanced
- [x] Make a smaller model (assembly), use OpenMC and the `openmc.mgxs.Library` API to create the data (this will probably be the same as, or similar to, the current mgxs-part-iv notebook and thus that notebook will be removed).  This library will use isotropic flux weighting and Legendre scattering of some order > 0.  This library will then be used directly in the MG mode
    - [x] Show the ability to change the Legendre order globally, and how to convert Legendres to/from Tabular representation globally
    - [x] End with local changes to scattering region, i.e., use anisotropic scattering in the water, isotropic elsewhere. Would be useful to note that the benefits of this arent as obvious with MC-MG since runtime doesn't scale with scattering order as strongly as a deterministic code (though I have no ability to prove that in this notebook, so this might not make it)
    - [x] The above will use the `convert_scatter_format(...)` method to change order, or at best go from Legendre to tabular; it should state in words what the possible options are for this code path.
- [x] With a pin-cell model, use OpenMC and the `openmc.mgxs.Library` API to create angular-dependent MGXS data; also will create histogram-based scattering representations directly through the API (vice via conversion).
    - [x] This data will then be used directly in MG mode, but this time making use of `create_mg_mode()` with a clear explanation that the method is useful only when the MG model geometry is exactly the same as the CE model that created the library.

**Comment by nelsonag** [comment]
I've got this mostly done.  I should add that the final major bullet will end up looking substantially different than the pin-cell model for angle-dependent libraries.  I actually switched to a rodded BWR 8x8 assembly.  This model had a strong dependence on angle (isotropically-weighted MGXS had a ~1000 pcm bias in the MG mode solver, and angular-dependent MGXS brought that down to 70pcm) which I think will make it easier to show the point of the angle-dependent MGXS.

I should add that the BWR assembly is heavily simplified; the rod pins are instead smeared, and since I'm using a mesh domain for the tracking, I fudged dimensions so the rod and intra-assembly water gaps match the pin pitch w/in the 8x8 assembly.  That will be explained in the notebook.

@wbinventor,@paulromano and anyone else: I want to ask thoughts on a re-organization of the example notebooks.  Right now they are located in the Python API section of the docs.  They are starting to not really be examples of 'how to use Python to interact with OpenMC', but now more like 'how to use OpenMC'.  The addition of these notebooks further shows that since they are really about using the multi-group mode, which happens to be using the PyAPI.  This is all to lead in to the following question: should all the example notebooks (current and proposed above) instead be moved to a top level of the docs?

**Comment by wbinventor** [comment]
I'm excited to see the new notebook(s) @nelsonag! I'm fine displaying the collection of notebook "recipes" more prominently on the website. Although I think they are fairly prominent already, many new users don't click on our "Python API" link. I've found myself directing them to that part of our site many times in the past. That said, I think @paulromano and @smharper and you should make this call.

**Comment by wbinventor** [comment]
On a related note, I think it would be cool to spruce up the hyperlinks for the different notebooks, regardless of where we choose to put them. If possible, it would be nice to use a representatve plot from each one as the link, similar to what is done to showcase examples on scikit-learn's website. People like to click on pretty figures more than they do boring text. This might not only direct more attention to the notebooks, but it would also add some flair to our website. Though perhaps such things influence me more than they should :-)

**Comment by paulromano** [comment]
I'm hoping in the next few weeks to do a major rewrite of our documentation, so this would be fair game. I think overall the Python API needs to be emphasized in our user's guide, reflecting the fact that we encourage people to use the API over writing XML files directly. Keep the suggestions flowing!

**Comment by nelsonag** [comment]
Closed by #818
