### ISSUE TITLE
Implement distribcell/mat algorithm in PyAPI

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/openmc#797]
It would be very helpful to implement the distribcell/mat algorithm directly into the PyAPI for input preparation and tally data processing. For example, it would help automate the preparation of distribmat inputs for pin-wise depletion calculations with @cjosey's OpenDeplete framework.

Although I haven't given too much thought to this, I would initially propose the following new additions to the PyAPI:

* `Geometry.get_num_instances(cell`/`material)` - return path of `cell` or `material` in the geometry
* `Geometry.get_path_to_instance(cell`/`material)` - return path of cell/universe/lattice IDs to reach a particular instance of a `cell` or `material`
* `Geometry.get_all_paths(cell`/`material)` - return an array of all paths of cell/universe/lattice IDs to reach all instances of a `cell` or `material`

These new "public-facing" methods might leverage several new "private" methods implemented on the `Cell`, `Universe` and `Lattice` classes to recursively count instances and build the paths to each instance.

**Comment by paulromano** [comment]
@wbinventor Are you planning on implementing these methods yourself at some point?

**Comment by wbinventor** [comment]
It was on my near-term agenda, since I may be the developer most familiar with the "distribcell" algorithm at this point. In fact I was planning to start on it today, after I remember how our Fortran code executes the algorithm :-)

**Comment by wbinventor** [comment]
I've started working on this on my "pyapi-distribcell" branch. Thus far I've introduced a new `Cell.num_instances` property which is initialized by the `Geometry.count_cell_instances()` method. This differs a little from what I proposed above with a `Geometry.get_num_instances(cell)` method. If anyone has any issues with this, let me know; otherwise I'll implement a `Material.num_instances` property and `Geometry.count_material_instances()` method in a similar fashion.

**Comment by paulromano** [comment]
Sounds more Pythonic to me :+1:

**Comment by wbinventor** [comment]
My first stab at this is now available in #813 - in particular, the total number of cell and/or material instances can be counted with the PyAPI. I have not yet implemented the more complicated code to get the "paths" through the CSG tree to each instance of a cell or material. If my understanding is correct, this is actually *not* needed by OpenDeplete, is that right @cjosey? If not, then I will likely leave that for another day if and when a use case arises.

**Comment by wbinventor** [comment]
Closed with #821.
