### ISSUE TITLE
Use MPI_Initialized?

### ISSUE THREAD

**Issue by RonRahaman** [mit-crpg/openmc#808]
Recently, initialize_mpi() was updated to take an intracomm as an argument.  However, the subroutine always calls MPI_Init().  If I already have already initialized MPI in another driver, then initalize_mpi() will crash.  

Would you consider calling MPI_Initialized first, to see if MPI_Init has already been called?

**Comment by paulromano** [comment]
Yes, good point; I'll submit a fix for that.

**Comment by wbinventor** [comment]
Closed with #810.
