### ISSUE TITLE
distance_to_boundary, intersection surfaces

### ISSUE THREAD

**Issue by nhorelik** [mit-crpg/openmc#81]
If a particle is moving along a ray towards the exact location of the intersection of two surfaces, distance_to_boundary may choose a problematic surfaced_crossed.  For example, consider a two-cell geometry consisting of a sphere of radius 2 inside z-cylinder of radius 4, between two z-planes at z=1 and z=-1.  One cell is defined as the inside of the sphere and the inside of the z-planes, and the other cell is the inside of the z-cylinder outside of the sphere between the z-planes.  The two z-planes and the z-cylinder have vacuum boundary conditions.  If a particle is travelling from inside the sphere exactly towards where the sphere intersects one of the z-planes, distance_to_boundary will compute the same distance for both the z-plane and the sphere, surface selected as surface_crossed will be the one that comes first in the surfaces list for the cell, which in some cases might be the sphere.  If this happens the particle will fail to leak when it's supposed to because cross_surface will think we're crossing the sphere, which doesn't have the vacuum boundary condition.

**Comment by bhermanmit** [comment]
@nhorelik, @smharper - is this still an issue?

**Comment by nhorelik** [comment]
It's probably safe to close this issue if no one has run into this in practice.  If ever someone tries to implement a raytrace plotter it might crop up again.

**Comment by paulromano** [comment]
Closing this for now. We can always re-open later if it becomes a problem.
