### ISSUE TITLE
Multi-group tallies with energy out filter invert order of tally data

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/openmc#816]
When using an energy out filter on a tally in multi-group mode, the tally data is printed out in `tallies.out` such that the data for the highest energy groups are assigned to the lowest energy group (see below for the pincell_multigroup test problem with a tally added with an energy out filter). I believe this error also inverts the data in the Python API as well.

 =======================>     TALLY 2: TALLY 2     <========================

 Outgoing Energy [1.00000E-05, 6.35000E-02)
   Mesh Index (1, 1, 1)
     Total Material
       Nu-Fission Rate                      0.785271       +/- 3.73627E-03
 Outgoing Energy [6.35000E-02, 10.0000)
   Mesh Index (1, 1, 1)
     Total Material
       Nu-Fission Rate                      0.544718       +/- 2.96256E-03
 Outgoing Energy [10.0000, 100.000)
   Mesh Index (1, 1, 1)
     Total Material
       Nu-Fission Rate                      4.26199E-04    +/- 7.75768E-05
 Outgoing Energy [100.000, 1000.00)
   Mesh Index (1, 1, 1)
     Total Material
       Nu-Fission Rate                      0.0            +/- 0.0
 Outgoing Energy [1000.00, 5.00000E+05)
   Mesh Index (1, 1, 1)
     Total Material
       Nu-Fission Rate                      0.0            +/- 0.0
 Outgoing Energy [5.00000E+05, 1.00000E+06)
   Mesh Index (1, 1, 1)
     Total Material
       Nu-Fission Rate                      0.0            +/- 0.0
 Outgoing Energy [1.00000E+06, 2.00000E+07)
   Mesh Index (1, 1, 1)
     Total Material
       Nu-Fission Rate                      0.0            +/- 0.0

**Comment by nelsonag** [comment]
Closed by #817
