### ISSUE TITLE
PugiXML issue with older g++

### ISSUE THREAD

**Issue by cjosey** [mit-crpg/openmc#822]
Tested with GCC 4.8.4, GCC 5.4.0, and GCC 6.3.1.  Fails in the first two.

The PugiXML API has a preprocessor variable, ``PUGIXML_HAS_LONG_LONG`` that is only set to ``True`` if ``__cplusplus >= 201103``, or in other words, it exposes C++11 support.  By default, all versions of GCC prior to 6.0 default to ``__cplusplus = 199711``.

This preprocessor variable enables the ``to_llong()`` functions.  These are used in the C wrapper without preprocessing guards, so compilation will fail with the older standard.

Explicit C++ flags need to be added somewhere in ``CMakeLists.txt``.

**Comment by paulromano** [comment]
I was able to get it to work with gcc 4.8 (and Travis does too). This line in CMakeLists.txt should handle it:
```CMake
set_property(TARGET pugixml PROPERTY CXX_STANDARD 11)
```
This causes the `-std=gnu++11` flag to be used, which in turn makes `__cplusplus` be `201103`. Maybe your CMake version is too old? What version are you using?

**Comment by cjosey** [comment]
Yup, that solves it.  The default CMake in CentOS/RHEL is 2.8.12.2.  If I install the cmake3 package, it now works.

It appears that ``CXX_STANDARD`` was first added in CMake 3.1.3.  Should I just PR a change switching the required CMake version to 3.1.3 in ``CMakeLists.txt``?

**Comment by paulromano** [comment]
Hmmm, that's weird because Travis uses Ubuntu 14.04 which only has 2.8.12.2 as well. Let me investigate further.
