### ISSUE TITLE
ScattterMatrixXS.print_xs() fails with histogram bins

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/openmc#828]
The `ScatterMatrixXS.print_xs()` method fails when the `scatter_format` property is set to `'histogram'` for the outgoing angular representation. I noticed this while checking that the histogram representation works for consistent scattering matrices introduced in PR #807. Since this an issue that plagues both the current `ScatterMatrixXS` class as well as the new consistent formulation, and since the histogram binning is @nelsonag's baby, he might want to take a look into this.

**Comment by nelsonag** [comment]
Ah, good catch. There should be another loop within the inner loop of the print which deals with histogram bins.

**Comment by nelsonag** [comment]
I will get to that after #807 is merged
