### ISSUE TITLE
Problem selecting root universe for older models

### ISSUE THREAD

**Issue by tjlaboss** [mit-crpg/openmc#829]
I'm working with an older, pre-existing OpenMC model of TREAT. The model only exists in xml (not created through the Python API).

The old model has a lot of universes, not all of which are used to fill cells. Since commit 8be6a5860360503da0ae9779dd51b699e12cfce9, OpenMC no longer detects that the TREAT model's Universe 0 is the root universe.

If OpenMC can't find an obvious root universe through the new method, it would be useful to default to Universe 0 and call a warning (not a fatal error).

**Comment by paulromano** [comment]
Hmm, interesting point. What is the reason for having universes that are not used anywhere?

**Comment by tjlaboss** [comment]
Good question. I don't know: this is an old model not made by me. (You can see the geometry xml here in this private repo: https://github.com/mit-crpg/treat/blob/master/original/geometry.xml)

I'm not sure why there are universes that aren't used, but there's a whole lot of XML I'd have to go through by hand to find out which they are. A workaround would be nice, and there are probably other legacy models that could have the same issue in the near future

**Comment by paulromano** [comment]
No need to do that by hand -- a short script can be used to inspect the geometry to see which universes are not used. I'll take a stab at that and let you know what I find.

**Comment by paulromano** [comment]
Here's a quick script I wrote that will find universes that are not used:
```Python
#!/usr/bin/env python

import xml.etree.ElementTree as ET

universes = set()
fill_universes = set()

tree = ET.parse('geometry.xml')
for cell_elem in tree.findall('cell'):
    u = int(cell_elem.get('universe'))
    universes.add(u)

    if 'fill' in cell_elem.keys():
        fill = int(cell_elem.get('fill'))
        fill_universes.add(fill)

for lattice_elem in tree.findall('lattice'):
    u = int(lattice_elem.get('id'))
    universes.add(u)
    for u in lattice_elem.find('universes').text.split():
        fill_universes.add(int(u))

print('Universes not used as a fill: {}'.format(universes - fill_universes))
```
When I run this on your geometry.xml file, it says universes 0 and 6 are not used as fill, so universe 6 is the culprit.

**Comment by tjlaboss** [comment]
Thanks Paul, the model works with the extra universe removed.
