### ISSUE TITLE
Allow root universes with id != 0

### ISSUE THREAD

**Issue by smharper** [mit-crpg/openmc#843]
Workshops have a special magic that makes our little idiosyncrasies very apparent.  One thing I noticed at the last one is that it's quite silly that we require the root universe to be given the `id` of 0.  I think we can probably modify the code to accept an optional element in geometry.xml specifying the id of the root universe.

**Comment by paulromano** [comment]
I actually fixed this in #821. Done!

**Comment by smharper** [comment]
Nice!
