### ISSUE TITLE
Use fewer `.id`s in the PythonAPI

### ISSUE THREAD

**Issue by smharper** [mit-crpg/openmc#844]
Another tricky one to explain at workshops:  We sort of try to hide the concept of `id` numbers from the user by making them an optional keyword argument in most of our constructors, but you still need to use them when you create a `TallyFilter` or specify a `Plot.col_spec`.  I would like to make those objects accept e.g. `Cell` objects and grab their `id`s at export time.

**Comment by paulromano** [comment]
Totally agree -- let's fix that. The `Plot` one was already taken care of in #826, so specifying IDs when using filters is the last remaining area where you have to manually say `.id`. I guess the reason we use IDs is that if you read back a `Tally` object from a statepoint, it won't be able to recreate the same object unless the summary file is linked. These days that's usually a good assumption since we write summary.h5 by default, but the question then is what to store for filter bins when no geometry information is available.

**Comment by smharper** [comment]
Maybe we can avoid that question by only ever storing `id`s on the `TallyFilter`s.  We can adjust the `bins.setter` method to simply strip the `id` numbers from e.g. `Cell`s passed to it.  In other words, make these two options have identical effects:
```python
openmc.CellFilter([c.id for c in cells])
openmc.CellFilter(cells)
```

In the long run, there are probably advantages to storing the `Cell`s themselves, but I think we can quickly implement the `id` stripping now and have something which is better than the status quo.

**Comment by paulromano** [comment]
Yeah, I was thinking that too. Do you want to implement this or should I take it?

**Comment by paulromano** [comment]
Or, we can have a newcomer try to attack this since it is relatively simple.

**Comment by smharper** [comment]
I'm assigning @giudgiud.  I don't see a way to assign him with the official GitHub thing.  Maybe he has to be a collaborator first?

**Comment by smharper** [comment]
To be a little more explicit about the proposed change:

Consider this example of creating a CellFilter:
```python
filter = CellFilter([1, 2, 3])
```

That always calls this method you see defined for the `Filter` class in filter.py
```python
    @bins.setter
    def bins(self, bins):
        # Format the bins as a 1D numpy array.
        bins = np.atleast_1d(bins)

        # Check the bin values.
        self.check_bins(bins)

        self._bins = bins
```

We want this method to be a little bit smarter so that we can do something like
```python
c1 = openmc.Cell(cell_id=1)
c2 = openmc.Cell(cell_id=2)
filt = openmc.CellFilter([c1, c2])
```
or
```python
m1 = openmc.Material(material_id=1)
m2 = openmc.Material(material_id=2)
filt = openmc.MaterialFilter([m1, m2])
```

The most obvious approach would be to overload the `bins.setter` method for each of the relevant filters.  For every filter where we add a `bins.setter`, it probably doesn't make sense to keep a separate `check_bins` method.  So for `CellFilter` you would define something like
```python
    @bins.setter
    def bins(self, bins):
        # Format the bins as a 1D numpy array.
        bins = np.atleast_1d(bins)

        # Make sure the bins have the right content.
        cv.check_iterable_type('filter bins', bins, (Integral, openmc.Cell))

        # Strip ids from Cells.
        if any([isinstance(b, openmc.Cell) for b in bins]):
            if isinstance(bins[0], openmc.Cell)
                bins = np.atleast_1d(
                    [b.id if isinstance(b, openmc.Cell) else b
                     for b in bins])

        self._bins = bins
```

You would need to modify `UniverseFilter`, `MaterialFilter`, `CellFilter`, `CellbornFilter`, and `DistribcellFilter`.  We should also probably modify test_tallies.py so that it tests this feature and the examples so that they demonstrate this feature.

**Comment by paulromano** [comment]
Has there been any progress on this? I don't mean to rush it, but I would like to fix this before our next release and it is one of the last remaining issues tagged to v0.9.

**Comment by smharper** [comment]
@GiudGiud is short on time atm so I just demonstrated the PR process instead
