### ISSUE TITLE
Moving to a Python 3-only codebase

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#873]
Eventually, Python 2 will be [retired](https://pythonclock.org/). If and when this happens, we would be wise to move our Python codebase to support Python 3 alone (some might even argue Python 2 support should be dropped [before 2020](http://www.python3statement.org/)). I just wanted to create an issue to keep track of things we'd like to change when the switch to Py3 happens. Some changes off the top of my head:
- Remove use of `six` module
- Use `temporaryfile.TemporaryDirectory()` instead of `mkdtemp()`
- Use `super()` notation for subclasses

If you can think of other things, feel free to comment on this issue.

**Comment by nelsonag** [comment]
no need for importing from future

**Comment by cjosey** [comment]
I made Opendeplete py3 only for concurrent futures and LZMA.  Concurrent futures might be useful if the API had a parallelizable bottleneck, as it's just so easy to implement, but I'm unaware of any.  LZMA is useless if you're using HDF5.

Reading up the general differences:
I could see some usability in the faulthandler API.  It keeps traces if the script crashes so long as it's not ``kill -9``-ed.  Might be useful in C/Python linkages, at least for debugging.

Enums might help get rid of some of the random constants we have laying about.

I love unicode variables (almost all of my research scripts written in Julia use them extensively), but I'd leave the decision to allow or deny that in the style guideline to the rest of you.  It requires adding something like latex tab completion in your editor to be productive with it, but it makes things so much more readable and compact.

``os.path.join(a,b)`` can be replaced with ``a / b``.

That's about all I can find in a quick search.

**Comment by paulromano** [comment]
Didn't know about the `os.path.join` replacement (using `pathlib.Path`). Pretty nice!

One more I thought of -- using [`subprocess.run`](https://docs.python.org/3/library/subprocess.html#subprocess.run) from Python 3.5.

**Comment by paulromano** [comment]
Type annotations, the `typing` module, and the `typecheck-decorator` third-party package could simplify all our dynamic type checking.

**Comment by paulromano** [comment]
Class decorators provide some nice metaprogramming possibilities. For example, the `IDManagerMixin` class could be replaced with a class decorator, and the wrapped class wouldn't need to define `next_id` and `user_ids` class attributes.

**Comment by paulromano** [comment]
I'd like to propose that we do one more release (0.10) supporting Python 2 and then after that move to supporting Python 3.4+ only (Python 3.3 just hit [end of life](https://www.python.org/dev/peps/pep-0398/#x-end-of-life)).

Two other Python 3 things we can adopt:
- I wanted to use the optional `default` argument of max but found out that it is Py3-only.
- For documentation builds, we can get rid of the try/except for importing `unittest.mock`.

**Comment by smharper** [comment]
Closed with #965.  There are a few ideas here we haven't implemented, but the main point of this issue is definitely addressed.
