### ISSUE TITLE
Fixed Source flux tallies

### ISSUE THREAD

**Issue by walshjon** [mit-crpg/openmc#885]
I'm observing some apparently suspect behavior with flux tallies in a fixed source problem.

I'm intending to model a monodirectional beam normally-incident on a slab with tallies for the flux in 1) a vacuum region in front of the slab, 2) the slab, and 3) a vacuum behind the slab.  (Really, I just want the transmission (e.g., a current tally with a surface filter), but it seems like this has to be derived from flux tallies given the currently-imlemented type/filter combos)

The tally output pasted below shows identical flux in all three regions.  Given my interpretation of the inputs below, this seems to be a bug.  Is that right, or have I modeled something other than what I intended?

Thanks,
Jon

=============>     TALLY 1: INCIDENT-AND-REFLECTED-FLUX     <==============

 Total Material
   Flux                                 22.4181        +/- 2.75088E-02

 ======================>     TALLY 2: SLAB-FLUX     <=======================

 Total Material
   Flux                                 22.4181        +/- 2.75088E-02

 ==================>     TALLY 3: TRANSMISSION-FLUX     <===================

 Total Material
   Flux                                 22.4181        +/- 2.75088E-02

<?xml version="1.0"?>
<tallies>

  <tally id="1">
    <name>incident-and-reflected-flux</name>
    <filters>1</filters>
    <estimator>tracklength</estimator>
    <scores>flux</scores>
  </tally>
  <tally id="2">
    <name>slab-flux</name>
    <filters>2</filters>
    <estimator>tracklength</estimator>
    <scores>flux</scores>
  </tally>
  <tally id="3">
    <name>transmission-flux</name>
    <filters>2</filters>
    <estimator>tracklength</estimator>
    <scores>flux</scores>
  </tally>

  <filter id="1">
    <type>cell</type>
    <bins>1</bins>
  </filter>
  <filter id="2">
    <type>cell</type>
    <bins>2</bins>
  </filter>
  <filter id="3">
    <type>cell</type>
    <bins>3</bins>
  </filter>

</tallies>

<?xml version="1.0"?>
<geometry>

  

  <surface id="1"  type="x-plane" coeffs="-1.0" boundary="vacuum"/>
  <surface id="2"  type="x-plane" coeffs="0.0" />
  <surface id="3"  type="x-plane" coeffs="10.1" />
  <surface id="4"  type="x-plane" coeffs="11.1" boundary="vacuum"/>
  <surface id="5"  type="y-plane" coeffs="0.0" boundary="reflective"/>
  <surface id="6"  type="y-plane" coeffs="1.0" boundary="reflective"/>
  <surface id="7"  type="z-plane" coeffs="0.0" boundary="reflective"/>
  <surface id="8"  type="z-plane" coeffs="1.0" boundary="reflective"/>
  <cell id="1"  material="2" region="1 -2 5 -6 7 -8" />
  <cell id="2"  material="1" region="2 -3 5 -6 7 -8" />
  <cell id="3"  material="2" region="3 -4 5 -6 7 -8" />

</geometry>

<?xml version="1.0"?>
<materials>

  

  
  <material id="1">
    <density units="sum" />
    <nuclide name="U234" ao="2.8672e-07" />
    <nuclide name="U235" ao="1.0058e-04" />
    <nuclide name="U236" ao="1.1468e-06" />
    <nuclide name="U238" ao="4.7677e-02" />
  </material>

  <material id="2">
    <density units="sum" />
    <nuclide name="U238" ao="1.0e-100"/>
  </material>

</materials>

<?xml version="1.0"?>
<settings>

  

  <run_mode>fixed source</run_mode>
  <batches>500</batches>
  <particles>1000</particles>
  <ptables>true</ptables>
  <source>
    <space>
      <type>point</type>
      <parameters>
        -0.99999 0.5 0.5
      </parameters>
    </space>
    <angle>
      <type>monodirectional</type>
      <reference_uvw>1.0 0.0 0.0</reference_uvw>
    </angle>
    <energy>
      <type>discrete</type>
      <parameters>1.0e6 1.0</parameters>
    </energy>
  </source>

</settings>

**Comment by walshjon** [comment]
I generated these inputs based on the "separate filter/tally" documentation but was not using the updated source.  Classic user error.  It's still somewhat unexpected to me that the tally specification above was accepted by the pre-commit code and produced the results it did, though.

**Comment by paulromano** [comment]
Hmm, yeah I hear you. The reason it proceeded with no errors is because it essentially ignores XML elements that it isn't expecting. So, each of your tallies didn't effectively have any filters, hence why they all returned the same value. Anyway, glad you were able to figure it out quickly!
