### ISSUE TITLE
Nuclides with partial S(alpha, beta) tables

### ISSUE THREAD

**Issue by smharper** [mit-crpg/openmc#895]
Some reactor materials have isotopes which appear in a mixture of different molecular structures.  For example, the carbon in TREAT fuel assemblies is usually treated as a mixture of graphite and amorphus carbon.  In these cases, we need to apply S(alpha, beta) tables to only a fraction of the atoms in that material.

I've made a [branch](https://github.com/smharper/openmc/tree/partial_sab) that I believe implements all the necessary code.  I still need to update docs/relaxNG/tests, but that might take a while as I'll be out of town for a bit.  @tjlaboss, can you test this branch and make sure it gives the expected results for your problem?  To use it, set the optional `fraction` argument when calling `material.add_s_alpha_beta`.

**Comment by tjlaboss** [comment]
The new branch does give the expected results: the MCM core of TREAT is now critical.

**Comment by tjlaboss** [comment]
It should be noted that this addition breaks part of the test suite--it will need to be updated to include the `fraction` field in the `<sab>` element.
