### ISSUE TITLE
run_tests.py fails to detect the location of mpiexec

### ISSUE THREAD

**Issue by tjlaboss** [mit-crpg/openmc#896]
The script [`run_tests.py`](https://github.com/mit-crpg/openmc/blob/develop/tests/run_tests.py) fails to detect the correct location of the `mpiexec` executable. @cchaugen and I encountered this issue on computers running macOS Sierra 10.12.5 and El Capitan 10.11.6.

`run_tests.py` fails with the following error message: `FileNotFoundError: [Errno 2] No such file or directory: '/bin/mpiexec'`. (See [LastTest_hdf5-normal.log](https://github.com/mit-crpg/openmc/files/1093109/LastTest_hdf5-normal.txt))

The correct location of `mpiexec` on my machine is `miniconda/bin/mpiexec`; Carl's is in `/usr/local/bin/mpiexec`.

Note: the individual test scripts run fine in their respective directories.

**Comment by smharper** [comment]
Set the `MPI_DIR` environment variable, e.g. `export MPI_DIR=/usr/local/`

**Comment by tjlaboss** [comment]
...duh, thanks.

**Comment by smharper** [comment]
Don't sweat it.  There are so many knobs to twiddle on this big machine that it's hard to know where to find them all.

@cchaugen, does this fix all the test failures you emailed me about?
