### ISSUE TITLE
Cross section generation error

### ISSUE THREAD

**Issue by GiudGiud** [mit-crpg/openmc#940]
Hello,

When installing openmc for two new crpg developers and users, with nndc cross sections, openmc crashes when loading cross sections. 

The issue can be fixed by downloading from another source a set of hdf5 cross sections. 
@smharper and I suspect h5py got updated and it broke the conversion of ace to hdf5

When updating my h5py and the python hdf5 (dependent of h5py probably)
    h5py:           2.7.0              --> 2.7.1
    hdf5:           1.8.17-1          --> 1.10.1
I re-created the error :

Reading U234 from /home/g_giud/openmc/data/nndc_hdf5/U234.h5
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) MPI-process 0:
  #000: ../../hdf5-1.8.15-patch1/src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../hdf5-1.8.15-patch1/src/H5Fint.c line 1085 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../hdf5-1.8.15-patch1/src/H5Fsuper.c line 294 in H5F_super_read(): unable to load superblock
    major: Object cache
    minor: Unable to protect metadata
  #003: ../../hdf5-1.8.15-patch1/src/H5AC.c line 1320 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #004: ../../hdf5-1.8.15-patch1/src/H5C.c line 3574 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #005: ../../hdf5-1.8.15-patch1/src/H5C.c line 7954 in H5C_load_entry(): unable to load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #006: ../../hdf5-1.8.15-patch1/src/H5Fsuper_cache.c line 174 in H5F_sblock_load(): bad superblock version number
    major: File accessibilty
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) MPI-process 0:
  #000: ../../hdf5-1.8.15-patch1/src/H5A.c line 1660 in H5Aexists_by_name(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: ../../hdf5-1.8.15-patch1/src/H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
 ERROR: HDF5 data does not indicate a version. Your installation of OpenMC
        expects version 1.x data.
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0

**Comment by paulromano** [comment]
A few questions: are you using conda/conda-forge? Did you generate cross sections yourself (i.e., by running openmc-get-nndc-data) or did you download the pre-built cross sections (as described [here](http://openmc.readthedocs.io/en/latest/devguide/workflow.html#openmc-test-suite))? Can you actually open one of the cross section file with h5py? something like:
```Python
import h5py
f = h5py.File('U234.h5', 'r')
print(f.attrs['version'])
```

**Comment by GiudGiud** [comment]
Miniconda was used on both installs I think. I used it to re-create the problem.
We generated the cross sections ourselves, using openmc-get-nndc-data.
I can open the cross section file with h5py and print(f.attrs['version']) gives me : [1 0]

**Comment by paulromano** [comment]
It looks like a different version of HDF5 is getting linked in to the OpenMC executable. Notice in the error message:

HDF5-DIAG: Error detected in HDF5 (**1.8.15-patch1**) MPI-process 0:

The version of HDF5 that is used is indicated when you run CMake when building OpenMC. You'll want to make sure that you use the same version to generate the HDF5 data and run OpenMC. The specific cause of the error is because your library was generated with 1.10 and the format is not compatible with older versions of HDF5 (1.8.x and before).
