### ISSUE TITLE
Error writing tallies.out at least with gfortran 7.2

### ISSUE THREAD

**Issue by nelsonag** [mit-crpg/openmc#942]
I've stumbled upon a problem I've never experienced before.  I think this is due to an issue with gfortran 7.2, but that is only based on the fact that I've been away for a while and my distribution has since upgraded to 7.2, and now things fail.

Anyways, when writing a tallies.out file, the very first write command to that file produces an error:
```At line 155 of file /home/nelsonag/git/openmc/src/output.F90
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x7f32f8afe500 in next_record_w
	at /build/gcc/src/gcc/libgfortran/io/transfer.c:3775
#1  0x7f32f8affbbc in formatted_transfer_scalar_write
	at /build/gcc/src/gcc/libgfortran/io/transfer.c:2209
#2  0x7f32f8affe4c in formatted_transfer
	at /build/gcc/src/gcc/libgfortran/io/transfer.c:2279
#3  0x7f32f8b00a1b in data_transfer_init
	at /build/gcc/src/gcc/libgfortran/io/transfer.c:3200
#4  0x7f32f9feb598 in __output_MOD_header
	at /home/nelsonag/git/openmc/src/output.F90:155
#5  0x7f32f9fdd097 in __output_MOD_write_tallies
	at /home/nelsonag/git/openmc/src/output.F90:804
#6  0x7f32fa073215 in finalize_simulation
	at /home/nelsonag/git/openmc/src/simulation.F90:488
#7  0x7f32fa0761cf in openmc_run
	at /home/nelsonag/git/openmc/src/simulation.F90:119
#8  0x55dc6c83b03a in MAIN__
	at /home/nelsonag/git/openmc/src/main.F90:30
#9  0x55dc6c83b0a1 in main
	at /home/nelsonag/git/openmc/src/main.F90:3
```

I can get the same error by adding in my own custom write to tallies.out immediately after OpenMC opens the file.  As you would expect, the iostat return is negative, indicating an error, with the write statement, but that tells us nothing more than the above error and backtrace.

Has anyone else experienced this?

**Comment by paulromano** [comment]
I haven't upgraded to a distro with gfortran 7.2 yet, but I'll try to reproduce on an EC2 instance with Ubuntu 17.10. Is there a particular model that this happens on for you or is it just any model? Are you still running on Arch?

**Comment by paulromano** [comment]
@nelsonag I haven't been able to reproduce this behavior on Ubuntu 17.10 which uses gfortran 7.2

**Comment by nelsonag** [comment]
It still happens on any model, and yes, still on Arch.  Odd.

**Comment by nelsonag** [comment]
Little progress, but I do have more information:
- Running INQUIRE on the unit handler tells me that the IOSTAT error code is 5018; this is an internal gcc error code: 5018  LIBERROR_INQUIRE_INTERNAL_UNIT.  I cannot tell you why libgfortran is throwing that error through.
- I also learned that Arch is on gfortran 7.2.1 but Ubuntu is on 7.2.0.  There is a minor update to 7.2.1 in the testing repos for Arch now, maybe there is hope.  Looks like in the past month the file in question has been touched a few times.

**Comment by paulromano** [comment]
That's weird -- the GCC page itself does not show a 7.2.1 release (the most recent is 7.2.0). I also see that the Arch repositories say 7.2.1.

**Comment by paulromano** [comment]
One other update -- I did a source build of gcc 7.2.0 to see if things would be different from the prebuilt version on Ubuntu 17.10, but it still works perfectly fine for me.

**Comment by nelsonag** [comment]
Welp, the new gfortran patch was pushed; it works great.   So, 7.2.1 20171224 fixe the bug.
