### ISSUE TITLE
how to set up ACE cross section libraries OpenMC 0.9.0

### ISSUE THREAD

**Issue by milham99** [mit-crpg/openmc#947]
thank you for your great program,
when i run the modelling pin-cel file in ipython (i already install all necessery program), i got the error:
Reading settings XML file...
 Reading geometry XML file...
 Reading materials XML file...
 ERROR: No cross_sections.xml file was specified in materials.xml, settings.xml,
         or in the OPENMC_CROSS_SECTIONS environment variable. OpenMC needs such
        a file to identify where to find ACE cross section libraries.
Please can you help, thanks

**Comment by paulromano** [comment]
Setting up cross sections for your simulation is discussed at length in our [user's guide](http://openmc.readthedocs.io/en/v0.9.0/usersguide/cross_sections.html). Please give it a read and if you still need further assistance, I would encourage you to send a message to our [user's group](https://groups.google.com/forum/#!forum/openmc-users), openmc-users@googlegroups.com. That is generally the best place to ask these types of questions -- issues on GitHub are reserved for bugs, feature requests, and other development-related items.

**Comment by milham99** [comment]
Thanks you for your reply, i'm sorry to post it here. i will message the issue to the user's group, openmc-users@googlegroups.com. 

thank you
