### ISSUE TITLE
Beginner’s Guide link failure

### ISSUE THREAD

**Issue by zxkjack123** [mit-crpg/openmc#970]
The [A Beginner’s Guide to OpenMC](http://openmc.readthedocs.io/en/stable/usersguide/beginners.html) have two links fail to access the resources. 
In the 2nd last sentence, last paragraph, section 1.3: Another resource that is a bit more technical than the Reactor Concepts Manual but still at an elementary level is the DOE Fundamentals Handbook on Nuclear Physics and Reactor Theory [Volume I](http://energy.gov/sites/prod/files/2013/06/f2/h1019v1.pdf) and [Volume II](http://energy.gov/sites/prod/files/2013/06/f2/h1019v2.pdf).
There are `404 Page not found on server` error when click the links of Volume I and Volume II. 
Is this the permission problem or just because the files are no longer there?

**Comment by paulromano** [comment]
Thanks for reporting; I just submitted a pull request to fix the broken links.
