### ISSUE TITLE
3D Tally-Score Capability?

### ISSUE THREAD

**Issue by SterlingButters** [mit-crpg/openmc#971]
I have seen issue #815 and I understand that the statepoint does not possess 3d capability. If it does not have the capability, then what is the purpose of a 3D mesh dimension?:

```
# Find mesh dimensions - use 3D indices for simplicity
        if len(self.mesh.dimension) == 3:
            nx, ny, nz = self.mesh.dimension
        elif len(self.mesh.dimension) == 2:
            nx, ny = self.mesh.dimension
            nz = 1
        else:
            nx = self.mesh.dimension
            ny = nz = 1
```

I am still figuring things out but when I specify the mesh.dimension = [17, 17, 100] in the Multi-Group (Delayed) Cross Section Generation Part II: Advanced Features notebook, I don't see any effect, should I?

**Comment by SterlingButters** [comment]
In fact, if I make the settings.output = {'tallies': True} then the tallies.out provides the scores for the mesh in the dimensions that I specify, yet the values of the scores are 0 for anywhere in the mesh that z does not equal 1. Eg:

```
 Mesh Index (17, 17, 1)
   Incoming Energy [1.00000E-03, 3.27341E-03)
     Total Material
       Flux                                 1.18159E-04    +/- 2.04065E-05
       Total Reaction Rate                  3.61988E-04    +/- 5.35350E-05
       Kappa-Fission Rate                   5314.21        +/- 1599.57
       Flux-Weighted Inverse Velocity       1.84090E-09    +/- 3.07943E-10
       Prompt-Nu-Fission Rate               6.65179E-05    +/- 2.00218E-05
       Nu-Fission Rate                      6.69534E-05    +/- 2.01529E-05

Mesh Index (17, 17, 2)
   Incoming Energy [1.00000E-03, 3.27341E-03)
     Total Material
       Flux                                 0.0            +/- 0.0
       Total Reaction Rate                  0.0            +/- 0.0
       Kappa-Fission Rate                   0.0            +/- 0.0
       Flux-Weighted Inverse Velocity       0.0            +/- 0.0
       Prompt-Nu-Fission Rate               0.0            +/- 0.0
       Nu-Fission Rate                      0.0            +/- 0.0

Mesh Index (17, 17, 10)
   Incoming Energy [1.00000E-03, 3.27341E-03)
     Total Material
       Flux                                 0.0            +/- 0.0
       Total Reaction Rate                  0.0            +/- 0.0
       Kappa-Fission Rate                   0.0            +/- 0.0
       Flux-Weighted Inverse Velocity       0.0            +/- 0.0
       Prompt-Nu-Fission Rate               0.0            +/- 0.0
       Nu-Fission Rate                      0.0            +/- 0.0
```

**Comment by SterlingButters** [comment]
And running openmc-plot-mesh-tally on the statepoint file even lets me choose the axial level which is exactly what I want. (With returned values/plot obviously)

**Comment by paulromano** [comment]
Statepoint files do fully support tallies with 3D mesh filters. The purpose of the now-defunct `openmc-statepoint-3d` script was to create SILO or VTK files based on a statepoint containing a 3D mesh tally, so that particularly capability is not available at the moment. However, you can definitely still do tallies containing 3D mesh filters without issue.

Without seeing your model, I couldn't say for sure why you're getting zeros for some mesh elements. One thing I'll draw your attention to is that Mesh.width refers to the width of a single mesh element (rather than the entire mesh), so if you are using that attribute, make sure you're using it correctly.

**Comment by SterlingButters** [comment]
@paulromano  Thank you, I think I figured it out, I'm still getting some weird stuff but I think I just need to play around with it a bit.
