### ISSUE TITLE
Unhelpful Segfault With Extra Material

### ISSUE THREAD

**Issue by scopatz** [mit-crpg/openmc#978]
In class today, I ran across an issue in v0.10.0, where if a material is defined, but not used, OpenMC will segfault and not provide any information about the underlying cause. The error is something like:

```console
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7F4711F36407
#1  0x7F4711F36A0E
#2  0x7F4710EA713F
#3  0x7F4713660D55
#4  0x7F471367C78A
#5  0x7F471365C37A
```

A Jupyter notebook that reproduces this issue is available at https://gist.github.com/scopatz/67e1e44851b8e6dfbdbb773096c707bf

Let me know if you have any other questions.

**Comment by paulromano** [comment]
Thanks for reporting -- I'll look into it.

**Comment by smharper** [comment]
@scopatz, can you confirm this is closed?  I actually wasn't able to reproduce your error so I can't be sure.

**Comment by scopatz** [comment]
Hi @smharper - I don't have an OpenMC dev environment at the moment. Since I am teaching a class with OpenMC opted for something a little more stable (the conda-forge package). If you put out a micro-release, I'll happily test it then!

**Comment by paulromano** [comment]
I was able to reproduce the error based on the notebook that @scopatz shared, and I've confirmed that it no longer exists on the develop branch now that #979 was merged, so I'm going to go ahead and close this.
