### ISSUE TITLE
Including openmc.h

### ISSUE THREAD

**Issue by lindsayad** [mit-crpg/openmc#995]
If I run
```sh
cmake ..
make
```
the resulting `include` directory contains all the Fortran module files but it does not include `openmc.h`. If an external library wants to call through the C-API it would be great if that header file could be found in a standard `include` directory. Moreover, if I run `make install` the resulting installation directory doesn't even have an `include` directory.

**Comment by paulromano** [comment]
Good point -- I'm planning on putting in a pull request this week so I might piggy back a fix for this on that PR (unless you want to submit one yourself!)

**Comment by paulromano** [comment]
@lindsayad This should be fixed on the develop branch now.
